### ISSUE TITLE
Twin-transmission unable to turn at low speeds

### ISSUE THREAD

**Issue by A1ex-Andro** [Muushy/Sprocket-Feedback#102]
When turning at low speeds, tanks with twin-transmission should be able to brake the inside track so that power goes only to the outside.

Instead, tanks with twin-transmission in the game downshift the inner track to first gear but do not stop it. If the tank is travelling at a low speed, it will not turn. 

It's worth noting that a tank will often not turn unless the outside track is in 3rd gear or higher (which is another issue).

It would make sense to let the driver brake the inside track _if_ you release the "W" key while turning.

**Comment by Muushy** [comment]
Fixed in in V0.123. TTs will downshift the inner track to neutral if the outer track is in 1st gear.
