### ISSUE TITLE
Incorrect slope-climbing ability

### ISSUE THREAD

**Issue by A1ex-Andro** [Muushy/Sprocket-Feedback#103]
The ability of tanks in Sprocket to climb slopes is very incorrect. 

**How it is in reality:**

The horizontal component (relative to the tank) of the tank's weight is `mgsin(θ)`. The frictional force keeping the tank from sliding down is `f = μN`. The vertical component or normal force is `N = mgcos(θ)`. If the tank is stationary on the slope, the horizontal component of its weight and the frictional force are equal:
`mgsin(θ) = μmgcos(θ)`
Solving for the coefficient of static friction, we get:
`μ = sin(θ)/cos(θ) = tan(θ)`
This means that the coefficient of static friction is equal to the tangent of the maximum angle an incline can reach before the object on it will begin to slide down.

The coefficient of static friction for rubber-padded tracks on dry concrete is given as 0.7. This means that the angle of a concrete ramp can reach 35 degrees before a tank will begin to slide down it.

**A tank will be able to climb a 35 degree slope regardless of how weak the engine is, if the 1st gear is large enough.**

How large of a 1st gear is needed? Let's calculate:

Suppose a tank weighs 45 tons, has an engine producing 1810 Nm gross torque, and a sprocket with an 822 mm pitch diameter.

The force provided by the sprocket is `kTG/R`, where k is the overall efficiency, T is the engine torque, G is the overall gear ratio, and R is the pitch radius of the sprocket. Suppose that the efficiency is 70% (which is approximately what it is).

The horizontal component of the weight is `mgsin(θ)`, where m is the mass of the tank, g = 9.81, and θ is the angle of the concrete ramp.

If the tank is to climb the ramp without losing speed, these two opposing forces must be equal:
`kTG/R = mgsin(θ)`
Solving for the overall gear ratio:
`G = Rmgsin(θ)/(kT)`
`G = (0.411)(45000)(9.81)sin(35)/[(0.7)(1810)]`
`G = 82.14`

If the final drive is 10.0 as it is in the game, the 1st gear needs to be 8.21 for the specified tank not to lose speed when climbing a 35 degree incline.

**How it is in-game:**

If a tank has weak engine, the game will not let it climb a 30 degree slope, let alone 35 degrees, regardless of the size of the 1st gear.
The thickness of the tracks affects slope-climbing ability (wtf???) 
The game won't let a tank with 5 cm thick tracks climb 20 degree slopes, but might allow a tank with 20 cm thick tracks to climb 40 degrees (which would require a coefficient of friction of 0.84, impossible!).
The width of the roadwheels also affects slope-climbing ability in the game, though not nearly as much as track thickness does.

**Comment by Muushy** [comment]
Should be significantly better in V0.1247
