### ISSUE TITLE
Center of mass pinned at 0 0 0 coordinates

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#107]
The center of mass is located at 0 0 0 coordinates and is not affected by the vehicle shape, external parts (ex. trench tail) or anything else.
New in V0.120

**Comment by A1ex-Andro** [comment]
I'd say this an improvement, not a bug. The centre of mass in previous versions was always in the wrong place. It would often make a tank very rear-heavy, despite having all its armour concentrated on the front. Or it would make turrets with a rear overhang super-unbalanced, despite the reason for that overhang being to balance the long gun. Taking only the shape into account would give a very inaccurate location for the centre of mass. Having it be locked to the same coordinates on every tank is a welcome change. Coordinates of x=0 and y=0 are correct, but is the height at z=0 as well? It would make sense to have it be a bit higher than that, but then it might be too high for low-profile tanks. Either way, even having it at z=0 is better than how it was before.

As an example, here are some tanks for which the centre of mass's height is specified in their manuals:
- IS-3: 1125 mm from the ground (The tank has a 450 mm ground clearance, so the centre of mass is 675 mm above the floor)
- IS-4: 605 mm from the centre of the drivewheel (This would be 1200 mm from the ground. The ground clearance is 410 mm, so the centre of mass is 790 mm above the lowest point of the floor)

I did notice a bug associated with this however: moving the turret further (forwards or backwards) from the centre of the tank makes it turn a lot slower.

**Comment by Muushy** [comment]
It's intentional, until more accurate centre of mass calculation is in.
@A1ex-Andro Actual coordinates are (0, 0.25, 0)m above the hull floor (y-up in Unity).
