### ISSUE TITLE
Errors during attach/detach causing partial attach/detach, causing future instability.

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#108]
Example case:
An error during external fuel tank attach will partially attach the part, enabling collisions.
The fuel tank will still be in placement, detecting itself as a placement surface, constantly moving towards the camera.
This can also cause the tank to not work once spawned if the fuel tank is placed, though this is potentially caused by the initial error during attach/detach.

https://discord.com/channels/788349365466038283/879446071007379476/1005214998177513492
https://gfycat.com/timelypoorlice

**Comment by Muushy** [comment]
Probable fix in V0.123
