### ISSUE TITLE
Freeform boxes not disappearing when clicking on firepower

### ISSUE THREAD

**Issue by BritishmanSprocket** [Muushy/Sprocket-Feedback#113]
**Describe the bug**
When selecting the gun depression angle, the freeform boxes don't disappear and remain selectable. 

**Version**
0.121

**To Reproduce**
1. Change the turret in free form
2. Go to 'Firepower'
3. Adjust the Elevation Bar

**Expected behavior**
For the freeform selection boxes to disappear as to not be able to select them.

**Screenshots**
https://media.discordapp.net/attachments/879446071007379476/1005803514351603722/unknown.png

**Comment by Muushy** [comment]
Can't reproduce.
Likely a side-effect of another error.
