### ISSUE TITLE
Incorrect hitbox around concave freeform shapes

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#115]
Hitboxes can be incorrect around concave freeform shapes, gun marker gets stuck on them and it's also possible to hit this area.

![image](https://user-images.githubusercontent.com/109303520/183309277-8eb83dd9-b1f3-4dce-bac3-200907c18b01.png)
![image](https://user-images.githubusercontent.com/109303520/183309300-680143c1-9529-4d9c-9bde-a01e12143c1c.png)

**Comment by Muushy** [comment]
Engine limitation.
