### ISSUE TITLE
Lorem ipsum prompt when saving tank while enter freeform prompt is on-screen

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#118]
Trying to save a tank while the 'enter freeform' (or leave) prompt is on screen causes the lorem ipsum prompt to appear.
Specifically when overwriting a saved tank.

Requires restart to fix.

Having both prompts on screen breaks the game.

Similar issue as #111 , if not the same.

**Comment by Muushy** [comment]
Same issue as #111
