### ISSUE TITLE
Constrained turrets not obeying constraints for 1 rotation

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#137]
On some designs constrained turrets do a 360 before settling into their constraints and then working as intended.
Not all designs are affected.

Affected blueprint example:
[AMR.31.blueprint.zip](https://github.com/Muushy/Sprocket-Feedback/files/9393647/AMR.31.blueprint.zip)

**Comment by Muushy** [comment]
Fixed in V0.1253.
