### ISSUE TITLE
Enemy tanks can spawn without certain parts or their entire turret/hull

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#138]
On occasion, enemy AI tanks spawn without some parts or without their turret/hull.
Seen two cases on the new Defence scenario so far.
Cause unknown.

King Tiger enemy:
![image](https://user-images.githubusercontent.com/109303520/185906627-7169d643-550c-4326-8bbc-6323fc0b1464.png)

**Comment by Muushy** [comment]
Fix for missing parts in V0.1258.
