### ISSUE TITLE
Turrets disappear but still present in blueprint file 

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#143]
Sometimes turrets can disappear from the game but are still present in the blueprint file
Happens with simpler geometry turrets as well.

Affected tank:
![image](https://user-images.githubusercontent.com/109303520/185909110-2fe7fadd-9974-425c-ba57-88d4ccd952ae.png)

What's expected:
![image](https://user-images.githubusercontent.com/109303520/185908926-6025f86f-36aa-42e1-83af-ba2d58a77b33.png)

Missing part extracted out of the game and loaded into Blender despite the part not being present in game:
![image](https://user-images.githubusercontent.com/109303520/185909329-db72a8b1-f7fd-4341-bc18-f400f1effad4.png)

Affected blueprint:
[Autosave (1).zip](https://github.com/Muushy/Sprocket-Feedback/files/9393800/Autosave.1.zip)
This blueprint was made entirely in the game.

**Comment by Muushy** [comment]
Fixed in 0.2
