### ISSUE TITLE
Parts not deleting properly

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#153]
Parts sometimes don't get deleted properly and reappear when reloading the blueprint.

Example of parts reappearing even though they were deleted previously:
![image](https://user-images.githubusercontent.com/109303520/192771963-bee76468-7cb2-491d-8cbd-58d353747e46.png)

Example affected blueprint:
[early_tiger_hull_parts.zip](https://github.com/Muushy/Sprocket-Feedback/files/9664576/early_tiger_hull_parts.zip)

Solution:
Delete the parts in the file (very inconvenient (also not tested), no known other fix).

**Comment by Muushy** [comment]
Potentially the same issue as #143.

**Comment by DarioXN** [comment]
This one seems to be more common in recent 0.124 versions, also seems to happen with mirrored parts, the part selected gets deleted, but it's mirror either doesn't get deleted or disappears only to reappear after reloading the blueprint

**Comment by Muushy** [comment]
Fixed in 0.2
