### ISSUE TITLE
Generated fenders reverting to max height 

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#155]
Generated fenders occasionally revert to max height when loading a tank, inconsistent.

This blueprint does it on occasion, no known cause.
[ASDSS1.zip](https://github.com/Muushy/Sprocket-Feedback/files/9664621/ASDSS1.zip)

**Comment by Muushy** [comment]
Can't reproduce.
I've seen it once or twice when loading outdated blueprints so it's probably a forwards compatibility issue.
