### ISSUE TITLE
Blueprint reload button

### ISSUE THREAD

**Issue by fedethesniper** [Muushy/Sprocket-Feedback#162]
have a button near the tank name that reloads the blueprint, without going thorugh the blueprint selection menu

**Comment by Muushy** [comment]
UI Clutter that's only useful for file editing - which shouldn't be directly supported in-game.

**Comment by fedethesniper** [comment]
the point here was that some tanks failed to load properly at the first try, or as a form of fast undo if you botch a modification, I guess
