### ISSUE TITLE
Screen flashing black in V0.124

### ISSUE THREAD

**Issue by maxbernard3** [Muushy/Sprocket-Feedback#165]
Sometime the screen flash black when moving the camera in mission and builder

**Version**
V0.124

**To Reproduce**
1. Go to any mission
2. select any Anti-Aliasing **exept TAA**
3. move the camera around

**Video**
Epilepsi warning : 
[Video of testing diferent anti-aliasing](https://youtu.be/JgVuxuq215g)

**Additional context**
 - using a GTX-1660 ti and latest (V517.48) NVIDIA Drivers, native Windows 10 (V10.0.19043)
 - under any wether condition and any time of day in custom battle and mission
 - with any graphic setting, V-Sync on or off and any Anti-Aliasing **expept TAA**
 - stop when the game is posed
 - stop when in scope mode

**Comment by Muushy** [comment]
Fixed in V0.1241
