### ISSUE TITLE
Unable to load blueprints

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#167]
Some users cannot load blueprints in 0.124, the list is blank, this is the case for both existing and new blueprints.

![image](https://user-images.githubusercontent.com/109303520/193457261-3f7ae5e6-c26a-42eb-93c3-abb514c73ae2.png)

**Comment by Muushy** [comment]
Potential fix in V0.1242

**Comment by DarioXN** [comment]
Still present in 0.1242

![image](https://user-images.githubusercontent.com/109303520/195303524-36b84368-6e87-42c3-bc03-57979e3d2408.png)
