### ISSUE TITLE
Camera collision doesn't take into account the ground deforming

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#169]
The camera can clip through the ground in places where it is not deformed (tank hasn't driven over it yet).

![image](https://user-images.githubusercontent.com/109303520/193457397-4f03ad95-423b-4b6d-85f6-e41aedc549c0.png)

**Comment by Muushy** [comment]
Fixed in V0.12418

**Comment by DarioXN** [comment]
Appears in the new Taiga map.

![image](https://user-images.githubusercontent.com/109303520/217617482-ea83c3e0-1512-44cf-b470-9a5f16291ffe.png)

**Comment by Muushy** [comment]
Fixed in V0.12422

**Comment by DarioXN** [comment]
Happens with the deformable mud on No Tanks Land.

![image](https://user-images.githubusercontent.com/109303520/217890292-59cb68e5-8125-483a-9398-1c5434ad4365.png)

**Comment by Muushy** [comment]
Reduced in V0.124123.
