### ISSUE TITLE
Inconsistent texture scale on AI tanks

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#174]
The tank texture isn't the same scale across the entire tank, but only on AI tanks (and every tank in custom battles).
The bigger the face is, the bigger the texture.

Can be seen on the faces surrounding the dent.

![image](https://user-images.githubusercontent.com/109303520/193458413-c9c8d90b-6f7c-40b4-8972-00a0ac5443f5.png)

**Comment by Muushy** [comment]
Fixed in V0.12418
