### ISSUE TITLE
Able to select compartments while trying to select multiple points/edges/faces

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#180]
When selecting multiple points/edges/faces, it is possible to inadvertently select a different compartment if it is located in front of what the user is trying to select, this happens if the user is selecting things too quickly thus looking like they want to select a compartment (due to rapid clicks being seen as double clicking a compartment), this is mostly an issue when selecting multiple things, as otherwise rapid clicking isn't usually done.

My suggestion on a fix is disabling double click compartment selection while shift is being held down.

**Comment by Muushy** [comment]
Much less of a problem in 0.2
