### ISSUE TITLE
Reload progress bar gets stuck

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#182]
The reload progress bar gets stuck at it's last position if a custom battle is reset (by pressing space after the battle has finished) if the gun is reloading at that time.

Image shows the old bar under the current one.
![image](https://user-images.githubusercontent.com/109303520/196584301-1ce23309-946a-41b4-928b-50da289e05c9.png)

**Comment by Muushy** [comment]
Fixed in V0.1245
