### ISSUE TITLE
Camera drifts off of the cupola at high speed

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#187]
The camera drifts away from the cupola when the tank is moving at high speed, this is due to the camera moving moving towards the opposite direction of motion.

Potential fix would be gradually reducing the effect depending on zoom in third person?

(The tank in this image is moving to the left)
![image](https://user-images.githubusercontent.com/109303520/197099658-ffc6ae1b-a01e-4f46-864d-56190bd6eba8.png)

**Comment by Muushy** [comment]
Fixed in V0.1247
