### ISSUE TITLE
Camera clips with the cupola at lower scales

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#188]
The camera clips into the cupola when the cupola is smaller (or when it is scaled down in height), and the opposite is true when it is larger (and scaled up in height).

![image](https://user-images.githubusercontent.com/109303520/197100446-a22e97ca-d6d6-4f3c-a999-6951cd70c457.png)

**Comment by Muushy** [comment]
Fixed in V0.1247
