### ISSUE TITLE
'Custom mantlets' broken

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#189]
Tanks with custom mantlets are broken, gunner and sometimes even loader don't work correctly, this only affects the player tank and doesn't affect any AI tanks or any tanks in custom battles (only the tank that spawns on the designer platform is broken), switching away from the player tank "resolves" the issue, though the original tank is still non-functional.

**Comment by Muushy** [comment]
Fixed in V0.1246
