### ISSUE TITLE
Make the camera move from the center of the tank towards the cupola as the player zooms in

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#190]
Make the camera move from the center of the tank towards the cupola as the player zooms in, the camera is often off center due to most tank designs having the cupola off center as well.

Having the camera gradually move from being centered to centering on the cupola would keep the camera centered in most gameplay situations and also keep the 'first person' effect when zoomed in fully.

Example of camera being off center in a normal gameplay situation:
![image](https://user-images.githubusercontent.com/109303520/197101758-ab1215c4-acd4-4743-afba-7a8e0eb7a4c8.png)

**Comment by Muushy** [comment]
Implemented in V0.1247
