### ISSUE TITLE
Increase UI refresh rate to make the aim point move more smoothly 

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#191]
Increase or unlock the UI refresh rate to make the aim point move more smoothly, currently it seems to be running at a fixed refresh rate which is lower than the frame rate of the game (I am guessing it is fixed at 30fps (or even less), or less likely half (or some other fraction) 
of the game's frame rate).

In my situation it is very noticeable that the aim point is not as smooth as the rest of the game (30fps UI on a 144fps game).

**Comment by Muushy** [comment]
Turned out to be a bug - Fixed in V0.1247
