### ISSUE TITLE
Pause screen in main menu after custom battle

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#193]
Pressing escape after winning or losing a custom battle takes you back to the main menu but also opens the pause menu, causing it to display in the main menu.

Pressing the quit to main menu option causes it to go away and the game continues functioning as normal.

![image](https://user-images.githubusercontent.com/109303520/197131649-d01c72f6-5167-47e8-8968-a0a79c0f6279.png)

**Comment by Muushy** [comment]
Fixed in V0.1249
