### ISSUE TITLE
Smoothing is Bugged

### ISSUE THREAD

**Issue by A1ex-Andro** [Muushy/Sprocket-Feedback#195]
Just two examples:

**1.**

Wedge with 60 degree slope Angle
![Smoothing 6](https://user-images.githubusercontent.com/109421040/197330941-6ff32de2-5406-4a1d-8234-7f5b740ab838.jpg)
No Smoothing:
![Smoothing 4](https://user-images.githubusercontent.com/109421040/197330979-63877122-d2f1-414e-92bf-aefc80251db2.jpg)
31 degree smooth angle:
![Smoothing 7](https://user-images.githubusercontent.com/109421040/197330946-c1d52541-6dca-4002-b990-0d6c0c50b06c.jpg)
![Smoothing 5](https://user-images.githubusercontent.com/109421040/197330944-0207e5b6-9c2a-4b3c-a6a6-3d8a22be5d90.jpg)

**2.**

Flat roof, no smoothing:
![Smoothing 8](https://user-images.githubusercontent.com/109421040/197331031-bda73f45-4a6c-4624-92c8-c76a43959e9d.jpg)
With ~~60 degree smoothing~~ I meant to say 30 degree smoothing. It's the plate that's sloped at 60.
![Smoothing 9](https://user-images.githubusercontent.com/109421040/197331034-403935c8-81ce-404a-aaf4-297756d2492c.jpg)

**Suggestion: Make smoothing _visual only_. People only use it for that anyways. That way it can look good _and_ not ruin the armour profile.**

**Comment by Muushy** [comment]
Only real fix would be to lower the maximum smooth angle.
Decoupling the visuals from the armour doesn't seem like a good idea.

**Comment by A1ex-Andro** [comment]
That's how it is in WoT. The visual model is smooth, whereas the collision model is an unsmoothed mesh with each face having an armour value as in Sprocket. At the very least, there needs to be tickbox in the designer to make the smoothing visual only.

Lowering the maximum smooth angle won't fix it because both of these examples are for a smoothing angle of only 31 degrees. If the plate was sloped at 70 degrees, anything above 20 degrees would be enough to reproduce the bug.
