### ISSUE TITLE
Visual Width of Road Wheels is Different from the Specified Width

### ISSUE THREAD

**Issue by A1ex-Andro** [Muushy/Sprocket-Feedback#196]
A 0.2 m wide roadwheel compared to a 0.2 m wide turret:
![Screenshot 2022-10-22 051756](https://user-images.githubusercontent.com/109421040/197331704-9daef6b5-acb5-4cdf-b4ab-9000dc62e471.jpg)

**Comment by Muushy** [comment]
Fixed in V0.125.
