### ISSUE TITLE
Track pitch differs from the specified track link length

### ISSUE THREAD

**Issue by A1ex-Andro** [Muushy/Sprocket-Feedback#197]
Comparison of 0.2 m long track link and 0.2 m long turret:
![Screenshot 2022-10-22 052649](https://user-images.githubusercontent.com/109421040/197332013-c9bbb779-b27d-4846-ba5a-be92ca1e0424.jpg)
A 0.20 m track link appears as being 0.14 m long.

**Comment by Muushy** [comment]
Segment length describes the full length of a single segment, not the pin to pin distance.
![Unity_UpZtkCCL2Y](https://user-images.githubusercontent.com/46500242/198026857-19cc0d70-ac13-4d2d-9f7d-fb34cedfbd9d.png)

**Comment by A1ex-Andro** [comment]
The overall length of a single link is not a useful measurement and is never specified, unlike the track pitch length. Rename "length" to "pitch" and have it correspond to that.

**Comment by Muushy** [comment]
Changed in V0.125.
I've kept the "Length" name as it's more intuitive, though the slider now represents pitch.

**Comment by A1ex-Andro** [comment]
A good argument for using the correct term is that people learn things from this game.
