### ISSUE TITLE
Tracks over 3x lighter than they should be (+easy fix)

### ISSUE THREAD

**Issue by A1ex-Andro** [Muushy/Sprocket-Feedback#198]
For reference, I looked at the Panther's tracks links:
![image](https://user-images.githubusercontent.com/109421040/197333776-7bdba0b6-7046-4973-95da-a953e6923131.png)
Width: 660 mm
Thickness: 100 mm
Pitch: 150 mm
Number of links: 86
Weight of one track: 2050 kg

(0.66 m) x (0.1 m) x (0.15 m/link) x (86 links) = 0.8514 m^3
(2050 kg) / (0.8514 m^3) = 2408 kg per cubic metre of track

Now, the weight of each track in game can be calculated as follows:
Weight of one track = (2408 kg/m^3) x (width) x (pitch) x (total length)
Total length = (track pitch) x (number of links)

Note: needs track pitch length to be corrected first, see https://github.com/Muushy/Sprocket-Feedback/issues/197#issue-1419211626.

**Comment by Muushy** [comment]
Will be adjusted in upcoming balance updates.

**Comment by Muushy** [comment]
Implemented in V0.125.
