### ISSUE TITLE
Photo mode look sensitivity decreases when you move further away from your own tank

### ISSUE THREAD

**Issue by A1ex-Andro** [Muushy/Sprocket-Feedback#204]
When you use the WASD keys to move away from the tank that you're in control of, the look sensitivity decreases. When you move closer, it increases. I assume that the sensitivity is supposed to stay the same regardless of your location on the map.

**Comment by Muushy** [comment]
Can't seem to reproduce it on my end, and there's nothing obvious in code that would tie these together.
