### ISSUE TITLE
AI tanks move back and forth rapidly

### ISSUE THREAD

**Issue by ColsonThePCMechanic** [Muushy/Sprocket-Feedback#208]
**Describe the bug**
Enemy AI tanks move back and forth rapidly, inhibiting their ability to properly aim at an allied tank.

**Version**
Current game version: 0.1248

**To Reproduce**
1. Spawn an enemy AI tank (works best if they have a powerful engine) in the sandbox or in a custom battle

**Expected behavior**
Tanks should not wildly jump back and forth.

**Video Examples**
https://user-images.githubusercontent.com/84006238/199823383-fd48e62f-f95a-4630-99e0-74db91b182ea.mp4

**Comment by Muushy** [comment]
Driver AI improved in 0.2.24
