### ISSUE TITLE
Tank is decimated upon spawning in

### ISSUE THREAD

**Issue by some1ongithub** [Muushy/Sprocket-Feedback#212]
A tank works fine in the designer, but upon pressing play, all the crew members die and the tank is obliterated with all its parts, the tracks start twitching as well. I tested this tank in sandbox, on other maps it seems to work fine.

v0.1249

1. Download https://github.com/Muushy/Sprocket-Feedback/files/10016685/VTI-123-A.no.camo.exhaust.-.Copy.txt
2. change it to a blueprint file
3. Put it in the vehicles folder
4. Press play

I expected the tank to be playable outside of the designer, like it has prior to v0.1249

https://user-images.githubusercontent.com/55634803/202041399-b5d0b068-53b0-46e8-af9e-4d4ed2e6703e.mp4

This doesnt happen to the other variants i made of this tank, which contain no major differences, besides having no exhaust.
https://github.com/Muushy/Sprocket-Feedback/files/10016715/VTI-123-A.T.-.Copy.txt
https://github.com/Muushy/Sprocket-Feedback/files/10016720/VTI-123-A.no.camo.-.Copy.txt

**Comment by Muushy** [comment]
Looks like you've got an accidental extra compartment under the tank. That'll be what's causing it.
![Unity_9piKRLihsy](https://user-images.githubusercontent.com/46500242/202169931-15a45815-8148-448e-922e-fa0697a23d0d.png)

This should probably be caught by the game but that's a separate issue.
