### ISSUE TITLE
Rail tracks go underground on Railway 

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#213]
The rail tracks go underground on the Railway scenario.

To find the location go from the spawn point to the tracks, turn left and then follow them (this is still within map boundaries).

![image](https://user-images.githubusercontent.com/109303520/202107781-c4b413cd-ebbf-4b50-9dc1-636985f9e012.png)

**Comment by Muushy** [comment]
Fixed in V0.12410
