### ISSUE TITLE
Knocked off parts don't return at correct size

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#226]
Sometimes parts that are knocked off don't return to their original size when returning to the designer (likely extremely small and large parts).

![image](https://user-images.githubusercontent.com/109303520/202992604-4a0bff93-31f6-4499-8fa8-22abbc251968.png)

**Comment by DarioXN** [comment]
Seems to happen when the knocked off part gets culled if it's tank moves far enough away.

**Comment by Muushy** [comment]
Should be fixed in V0.12422.
