### ISSUE TITLE
Ammo cook-off effects stick in designer

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#228]
When a knocked off turret goes far enough away from it's tank, and has the ammo cook-off effect playing, these effects stuck around when returning to the designer.

![image](https://user-images.githubusercontent.com/109303520/202993624-45ddf1f0-05f4-41cd-ae83-6d1d062a5c48.png)

**Comment by Muushy** [comment]
Fixed in V0.12412
