### ISSUE TITLE
All shells losing velocity at the same rate, regardless of mass and calibre.

### ISSUE THREAD

**Issue by A1ex-Andro** [Muushy/Sprocket-Feedback#229]
I tested a 250 mm "pancake" and a 20 mm "arrow" by shooting at a target a fixed distance away. Both had the same initial velocity. To my surprise, the penetration was reduced by the same percentage in both cases. This means that both shells were losing velocity at the same rate!

As you may know, the drag force on a shell is `F=0.5ρv²CA`, where ρ is the air density (varies with temperature, 1.225 kg/m³ at 15 °C), v is the velocity, C is the drag coefficient, and A is the cross-sectional area. 

The cross-section is a circle, so the area is just A=πr². The cross-sectional area for the pancake is 156 times larger than that of the 20 mm arrow, so if we make them have the same mass (and we assume that they have the same drag coefficient, as they do now in Sprocket), then the pancake should decelerate 156 times quicker!

What if we just change the mass of the projectile? Hopefully you remember that F=ma, so you know that for the same drag force, a projectile that is twice as heavy should decelerate only half as quickly.

This issue is so noticeable that other people have already mentioned it on the Discord server, before I even wrote about it.

**Extra:**
Regarding the drag coefficient, C. It's supposed to change with velocity (it's a function of Mach number, where Mach 1 is the speed of sound which is 340 m/s at 15 °C, so Mach 2 is 680 m/s, Mach 3 is 1020 m/s, etc). Attached below is a curve of drag coefficient vs Mach number for two standard projectile shapes. Use the Type 1 for the WWI and Interwar eras (ie, before 1930), and Use the Type 6 for Earlywar and onwards. This reflects the shape of the projectiles used around that time.

[mcg1.txt](https://github.com/Muushy/Sprocket-Feedback/files/10095301/mcg1.txt)
[mcg6.txt](https://github.com/Muushy/Sprocket-Feedback/files/10095302/mcg6.txt)

**Comment by Muushy** [comment]
Shells are handled by the physics engine at the moment.
Switching to a custom model with the shell designer, which should fix this.

**Comment by Muushy** [comment]
Custom model implemented in 0.2 with correct drag force calculation.
Thanks for the mach drag coefficient info, very useful!
