### ISSUE TITLE
Xoffset slider for wheels

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#230]
An xoffset value for sprockets, idlers, road wheels & return rollers already exists in the tank file and works well, provided it is not taken too far (about +15cm/-5cm being the around limit (for things like return rollers and idlers, the positive offset can go higher, and for sprockets likely lower in both directions, if any at all)), it is still close enough to the actual collision of the wheels as is right now, this of course can be improved if you wish to do so.

It would have to be given an actual name like "base offset", "base spacing" or something else.

Things like this are possible with a modified xoffset value (this is at 15cm, which is 10cm above default):
![image](https://user-images.githubusercontent.com/109303520/205769478-1b906515-8763-4526-9aec-46ee7921c09e.png)

Whereas without it, it would be like this, requiring a significantly wider idler wheel in order for the track to be centered (the track is 48cm wide in this case):
![image](https://user-images.githubusercontent.com/109303520/205769877-3e6cf697-fbc6-41e2-aa58-7b85a41df4d8.png)

**Comment by Muushy** [comment]
Added in V0.125.
