### ISSUE TITLE
Save/Load icons in ammo menu

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#236]
There are save/load icons in the ammo placement menu when reloading from editor, they disappear when you select an ammo rack.

**Comment by Muushy** [comment]
Having difficulty reproducing this, any clear steps?

**Comment by DarioXN** [comment]
> Having difficulty reproducing this, any clear steps?

I'm not sure, I had it happen once but don't know how I did it, I'm pretty sure it was when I selected a rack that was already placed though, might be when loading a saved tank and then selecting a rack.

**Comment by DarioXN** [comment]
> Having difficulty reproducing this, any clear steps?

Renaming a rack and then spawning the tank and then returning to the designer causes them to appear for me
Upper right, the buttons don't do anything.
![image](https://user-images.githubusercontent.com/109303520/207758794-a0cc4f42-7c60-4f27-b4a2-bea5a15e7970.png)

**Comment by Muushy** [comment]
Yeah, wasn't syncing when loading the designer UI, like when returning to the designer.
Fixed in V0.12417.
