### ISSUE TITLE
Wrong ammo load timers for close ammo racks

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#238]
When placing ammo you can have a reload speed faster than the guns intended maximum reload speed, such as a 30mm with a 1.7s reload having ammo that displays a 1.4s reload instead.

**Comment by Muushy** [comment]
Not an exact issue, just needs to be made clearer.
The displayed rack reload is the base reload, which is then modified by crew efficiency/other factors.
