### ISSUE TITLE
Tanks spawned at an angle (not forward facing) have cannon rotation permanently offset

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#24]
AI tanks with multiple guns in the turret have their mantlets break and face sideways.
![image](https://user-images.githubusercontent.com/109303520/179044724-264c8c27-fb71-472f-b036-d46cd2401255.png)

**Comment by Muushy** [comment]
Think you could provide steps to reproduce this @DarioXN? 
The faulty blueprint would work too.

**Comment by DarioXN** [comment]
@Muushy Just spawning the tank does it in most cases
[KV-1-II.zip](https://github.com/Muushy/Sprocket-Feedback/files/9120681/KV-1-II.zip)
This tank does it for me every time, it is pretty high part count but I believe this is unrelated
Tested it by spawning it as an enemy on the sandbox map

**Comment by Muushy** [comment]
Found it was caused by rotating the mantlet so it's upside-down. Going to have to restrict mantlet rotation more.

**Comment by Muushy** [comment]
Stopped in V0.11913. Mantlet rotation locked upright around the vertical axis with Q/E (default).
