### ISSUE TITLE
Part size limits

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#241]
Currently there are certain pars who's limits are not as large or small as before, the currently known ones are:

-Wooden Trim Vane
-Rivets (Likely #237, rounding to 1 1)
-Crusader MG Turret
-MG-34 MG Port
-One or both of the vents, can't confirm
-Plates (the ones in the structural tab)
-Fenders (likely the placeable ones)
-T-34 Driver's Hatch
-Circular Hatch
-Square Split Hatch
-Trench Tail

There are likely more that haven't been reported yet.

Blueprint with all parts at max and min sizes in 0.123 for comparing: 
[Part Test.zip](https://github.com/Muushy/Sprocket-Feedback/files/10223201/Part.Test.zip)

**Comment by Muushy** [comment]
Fixed in V0.12413

**Comment by DarioXN** [comment]
There's still some parts that are affected, here's the list:
min = minimum size too big
max = maximum size too small
the opposites of these were not tested
The names here are their in-game names

- [x]  1. Crusader MG Turret **(min)**
- [x]  2. Bolton Stowage Box **(min)**
- [x]  3. MG-34 Port **(min)**
- [ ]  4. Shovel & Axe **(min and max)**
- [x]  5. Long Closed Bustle Rack **(min)**
- [x]  6. Short Closed Bustle Rack **(min)**
- [x]  7. Matilda II Mantlet **(max)**
- [x]  8. Pz38t Mantlet **(min)**
- [x]  9. Internal Mantlet **(min)**
- [x]  10. Circular Mantlet **(min)**
- [x]  11. Panther Mantlet **(min)**
- [x]  12. SU-85 Mantlet **(min)**
- [x]  13. Squared Mantlet **(min)**
- [x]  14. Barrel Cleaning Rods **(min)**
- [ ]  15. Fire Extinguisher & Cutters **(min and max)** 
- [x]  16. Log **(min)**
- [x]  17. Tiger Engine Vent **(min)**

Blueprint with all correct parts removed (might be some mistakes):
[Part Test B.zip](https://github.com/Muushy/Sprocket-Feedback/files/10233012/Part.Test.B.zip)

**Comment by Muushy** [comment]
All fixed in V0.12415.
Thanks for the updated part blueprint!
Crew tool maximums will stay as they are, since larger ones would get unwieldy.
