### ISSUE TITLE
Mantlets placed not facing forwards break

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#244]
Mantlet that are not forward facing break, to reproduce, place a mantlet on the side of a turret, test drive it, and then return to the designer.

![image](https://user-images.githubusercontent.com/109303520/207447992-eb0bb544-519a-449a-ab10-2062065bc795.png)

**Comment by Muushy** [comment]
Can't get mantlets to rotate.
Assumed to be fixed.
