### ISSUE TITLE
Collisions cause fuel tank fires.

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#249]
Crashing into anything at speed will cause the fuel tank to catch fire, and due to #239 it is invisible and cannot be extinguished.
Easier to cause with a lighter vehicle.

**Comment by Muushy** [comment]
Fixed in V0.12414

**Comment by DarioXN** [comment]
In 0.12414, instead of causing fires, the tank explodes immediately.

**Comment by Muushy** [comment]
Fixed in V0.12415
