### ISSUE TITLE
AI tanks are faster than the player tank

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#252]
AI tanks are faster than the player tank (player tank being the one that starts on the platform, AI being any other tank, even when the player is driving it).

The tank in this example just about reaches 42.21km/h on the flat sandbox, while it's AI ally that it spawns with easily reaches 48.64km/h (at this point it gets limited by the transmission, it would otherwise go even faster) despite them being identical.

This bug has likely been in the game for a while.

The example tank:
[T15E1.zip](https://github.com/Muushy/Sprocket-Feedback/files/10234821/T15E1.zip)

**Comment by Muushy** [comment]
Fixed in V0.1253.
