### ISSUE TITLE
Trench Crosser and Tree Death

### ISSUE THREAD

**Issue by MrKinetiCat** [Muushy/Sprocket-Feedback#253]
**Describe the bug**
Using a tank designed from the previous version, you can cause your own vehicle to hop a tree on the scenario tundra.
I have video proof of it as well.
https://youtu.be/M2GwyijdBAQ 
(this link should work, if it does not, check back in a few hours.)

**Version**
0.12143 (experimental branch)

**To Reproduce**
1. Load a tank with a trench crosser. 
2. Go backwards into a tree on the Tundra scenario. Any tree will do.
3. You might die this time, but try again with the trench crosser phasing into it.
3. Perish quickly and die.
 - If unable to replicate this bug and die, load up the tank from this google drive link and repeat the steps. 
 https://drive.google.com/drive/folders/1aIpWLA_KBNZX7WSM06oy8vXonWRfCze2?usp=sharing

**Expected behavior**
If the bug is to happen, you should immediately die and (possibly) be launched upwards.
If the bug is fixed, you should just be able to knock over the tree.

**Screenshots**
I don't have any screenshots, but the video should suffice.

**Additional context**
It seems to only happen when backing into a tree while you have the trench crosser phasing into it.

**Comment by Muushy** [comment]
Fixed in V0.12418
