### ISSUE TITLE
Saved guns do not list their propellant length correctly

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#256]
Title, they list some other massive number in meters, likely also want to change this to millimeters.
The load correctly.

![image](https://user-images.githubusercontent.com/109303520/208269767-e9a87f05-43da-49c9-bff1-ba0e69dd1463.png)
![image](https://user-images.githubusercontent.com/109303520/208269782-62005470-17d7-420c-b2e1-11456fde7523.png)
These are the same gun.

**Comment by Muushy** [comment]
Fixed in V0.12415
