### ISSUE TITLE
Tank reference shape

### ISSUE THREAD

**Issue by fedethesniper** [Muushy/Sprocket-Feedback#260]
A button that saves the current tank's shape as a semitransparent wireframe shape, to be used as reference when making a new variant of that tank.

Would also be great for "alternate history" tank variants, as users could download a replica and use that as reference directly in the builder, and later on it could help players to better visualize how much they've changed a tank currently in production in their campaign.

**Comment by Muushy** [comment]
Far more trouble than it's worth.
