### ISSUE TITLE
Weight limit message doesn't scale with budget size

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#264]
The weight limit message doesn't scale with budget size.

![image](https://user-images.githubusercontent.com/109303520/209065203-2e46de2f-5783-4837-a38c-fd06eb4b6aad.png)

**Comment by Muushy** [comment]
Budget size as in the gameplay setting?

**Comment by DarioXN** [comment]
> Budget size as in the gameplay setting?

Yes.

**Comment by Muushy** [comment]
Fixed in V0.12417.
