### ISSUE TITLE
Churchill fenders don't have names

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#272]
Title, they have the name of the flat fender.

![image](https://user-images.githubusercontent.com/109303520/210319012-4ea75742-cedd-4234-b307-72bafa9c100a.png)

![image](https://user-images.githubusercontent.com/109303520/210319055-8034c919-fcdf-4596-9d22-b5fc3923ddb3.png)

![image](https://user-images.githubusercontent.com/109303520/210319106-38465b41-24e6-4e7b-83b9-c7d11bcadeef.png)

**Comment by Muushy** [comment]
Fixed in V0.12417
