### ISSUE TITLE
Very noticeable pixelation on worn paint

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#274]
Title, at close to medium viewing distances, more noticeable on parts than the tank itself.

![image](https://user-images.githubusercontent.com/109303520/210321382-665d9a8e-2423-4df9-9180-b7bcb88e406c.png)

![image](https://user-images.githubusercontent.com/109303520/210321453-4ca05cf1-1b29-4198-85a5-a699a8034518.png)

**Comment by Muushy** [comment]
Effect reduced in V0.12417
