### ISSUE TITLE
Inconsistent validation on turrets and ammo racks placed on center

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#277]
When turrets or ammo racks are placed exactly in the centered (snapped to it when close enough) they often don't properly register as being inside / valid, moving them even slightly to either side makes them work.

Ammo racks sometimes doesn't start working from this, if they were originally placed in the exact centerline of the compartment, they often don't work no matter where they are placed.

Turret validation is also generally inconsistent, even upon reloading the same tank.

**Comment by Muushy** [comment]
Can't reproduce the centred issues.
Turret validation made more consistent in V0.12418, might fix the potential issues.
