### ISSUE TITLE
Returning to designer while in gunner view causes assembly failures 

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#281]
Returning to the designer while in the gunner's view often but not always causes the game to lock up until returning to the main menu.
The camera cannot be moved and the tank can't be driven.

**Comment by Muushy** [comment]
Fixed in V0.12418.

**Comment by DarioXN** [comment]
This one has returned in 0.12419

**Comment by Muushy** [comment]
Having trouble reproducing the returned one, any steps?

**Comment by DarioXN** [comment]
> Having trouble reproducing the returned one, any steps?

Seems to happen if you're driving an AI tank and then return to the designer.

**Comment by Muushy** [comment]
That was it, cheers Dario. Ended up leading to a big instability when returning to the designer.
Fixed in V0.12421.
