### ISSUE TITLE
Incorrect shadows on parts

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#287]
Some parts have incorrect shadows.

Examples:

![image](https://user-images.githubusercontent.com/109303520/212145682-49e324c3-4d4a-49c5-9922-501d76b10a0b.png)
(also happens on the T-34 roadwheel at least)

![image](https://user-images.githubusercontent.com/109303520/212145841-1c555fc1-c7a7-40cb-907d-9efabf07b2e1.png)

![image](https://user-images.githubusercontent.com/109303520/212146075-4e93d4f6-8b87-4d7d-98f9-814628f29aeb.png)

![image](https://user-images.githubusercontent.com/109303520/212146277-d6df2fa0-65a2-4eb4-b05e-f6982a0dc61c.png)

Shadows being cast from LOD models?

**Comment by Muushy** [comment]
Fixed in V0.12422.
