### ISSUE TITLE
Multi turret tanks with same guns cannot use ammo racks

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#294]
Tanks that have multiple turrets using the same guns (and thus same ammo) cannot use ammo racks from other turrets (this I suspect is intentional, though it doesn't throw an error upon spawning) but also cannot use the hull ammo rack if there is a rack present in any of the turrets (only the turret with the ammo will work, despite the one without being able to reach the hull ammo)

Working setup:
![image](https://user-images.githubusercontent.com/109303520/212960898-4f1cc641-715d-4e8e-a07a-e419aa015e7d.png)

This setup doesn't work, only the turret on the left of the image works, the other one cannot fire:
![image](https://user-images.githubusercontent.com/109303520/212961176-60ad8465-7273-4745-8449-8a88d69da292.png)

If ammo is present in both turrets, neither works.

**Comment by Muushy** [comment]
Fixed in V0.12419.
