### ISSUE TITLE
Unbalanced guns on scenario tanks

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#295]
The tanks in scenarios (basically) all have unbalanced guns, both in their moment of inertia, and their performance, some cannot even aim at enemies.

Some tanks also have no ammo racks present or have invalid ammo racks.

This zip contains all the default tanks rebalanced slightly to make them work.
[Vehicles.zip](https://github.com/Muushy/Sprocket-Feedback/files/10437578/Vehicles.zip)
Use them if you want to, if not, that's fine.

Changes are:
Reduced shell length 25% on all of them (to bring them close-ish to what they were before) except the Tiger 1, it's ammo was reduced by 500mm due to excessive performance for midwar (>200mm pen).
Balanced the guns on the ones that needed it by moving the gun recess slider and laying drive torque only.
Fixed ammo rack locations / added ammo racks if they were missing.
Fixed fenders on some of them resetting to 0 height (might reoccur though).

No mobility, armor or cosmetic changes were made, other than the gun recess slider.
One thing to note is that the Bennett seems to have an incorrect front hull shape, as evidenced by the floating rivets.

**Comment by Muushy** [comment]
All vehicles updated in V0.12418
Thanks for the updated vehicles. Though I updated the vehicles before seeing them, whoops...
