### ISSUE TITLE
Asymetrical suspension

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#299]
The suspension on one side of the tank is 1cm too far in / out.
Both torsion bar and HVSS are affected, but in opposite directions.

Left side:
![image](https://user-images.githubusercontent.com/109303520/213443371-71a53407-3089-4ab3-9495-38370ea1d5a8.png)

Right side:
![image](https://user-images.githubusercontent.com/109303520/213443450-8b7f3d10-0440-4f57-bb8a-221225acec77.png)

**Comment by Muushy** [comment]
Fixed in V0.12422.
