### ISSUE TITLE
Ammo cook-offs sometimes don't kill the tank

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#306]
Title, I've had it happen to allied tanks, enemy tanks and even my own tank.

I could still aim and shoot after this.

![image](https://user-images.githubusercontent.com/109303520/214484156-a0430a8f-1e6e-471e-ba06-c03baca0f6ff.png)

**Comment by Muushy** [comment]
Increased damage in V0.12422.
