### ISSUE TITLE
Strange looking contact shadows

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#311]
Contact shadows from medium distances (close to where they go away completely) look weird.

In this case it's being cast from the radio antenna onto the back of the turret:
![image](https://user-images.githubusercontent.com/109303520/216304901-41bef181-54e5-4f43-9359-947c72af3c1e.png)

**Comment by Muushy** [comment]
Max distance lowered in V0.1252.

**Comment by Muushy** [comment]
Realized these are being relied on for grass shadows. Max distance needs to stay the same.

**Comment by Muushy** [comment]
Going to have to stay. Contact shadows are never perfect.
