### ISSUE TITLE
Incorrect ground culling with deformable terrain turned on

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#313]
Title, very likely because the actual ground mesh is far below the deformable snow.

![image](https://user-images.githubusercontent.com/109303520/217618533-cf232022-3f31-4360-85c9-a621e134d4ed.png)

**Comment by Muushy** [comment]
Fixed in V0.12422.

**Comment by DarioXN** [comment]
Happens on NTL (a bit less noticeable).

![image](https://user-images.githubusercontent.com/109303520/217893978-f1b124fc-4b73-4429-8e57-eaf6cc04eaa6.png)

**Comment by Muushy** [comment]
Fixed in V0.12423
