### ISSUE TITLE
Changing graphics setting causes the screen to turn black and only show the UI

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#317]
Title, I tested it by changing graphics presets (from maximum to medium) while in the sandbox and not in the designer.

Later returned to the main menu to see if it fixes itself, it does not.
![image](https://user-images.githubusercontent.com/109303520/218290385-e9154859-1c5e-4f03-b254-df6b005350c7.png)

**Comment by DarioXN** [comment]
This one doesn't seem to happen anymore, or at least, I can't reproduce it like before.

**Comment by Muushy** [comment]
Probably shaky forward compatibility.
