### ISSUE TITLE
Missing SU-85 mantlet armor model

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#318]
Title.

![image](https://user-images.githubusercontent.com/109303520/218292009-f2ebeff5-1590-4bb0-b733-91f536d44144.png)
![image](https://user-images.githubusercontent.com/109303520/218292062-73ce3a96-de16-410e-819a-1b15124f0f17.png)

**Comment by Muushy** [comment]
Fixed in V0.12423.
