### ISSUE TITLE
Guns have incorrect moment of inertia

### ISSUE THREAD

**Issue by A1ex-Andro** [Muushy/Sprocket-Feedback#330]
I calculated it myself:
https://www.desmos.com/calculator/goepywem5o
Elevation was always manual, except in tanks with a stabilizer (like the American ones). Soviet tanks up to the early T-54 all had manual elevation only.
Manual elevation should be perfectly adequate even for large guns, as this calculator shows.

**Comment by Muushy** [comment]
Thanks Alex, very useful.
Fixed in 0.2.13.

**Comment by A1ex-Andro** [comment]
@Muushy I have an updated version of this:
https://www.desmos.com/calculator/fsl5x31yhm

The older version was calculating the moment of inertia for each frustum as if for a cone missing the top (the moment of inertia of a large cone minus the moment of inertia of the smaller cone that is cut off of it to make the frustum). However, as the difference between the start and end diameter of the frustum decreases, and it approaches the shape of a cylinder, the length of both the large and small cones becomes very large.

The newer version instead uses an equation for a frustum derived using calculus. There are significantly less equations as a result. I simplified the calculation steps in other ways as well.

There was also a mistake somewhere in the older version, which is unsurprising given the number of equations, that affects the moment of inertia and centre of mass. The newer version is correct.

**Comment by A1ex-Andro** [comment]
I should add that having the "counterweight" is still useful in the game. People would use it to adjust the centre of mass (and therefore the centre of rotation) of the gun to exactly match the tank they are attempting to make a replica of. Although the mass of the barrel will be identical to what they are replicating, the mass of the breech for the tank in question will differ somewhat from the generalisation used in-game.

**Comment by A1ex-Andro** [comment]
There is also a problem in the implementation. I made a gun with the same dimensions as the one in the calculator, 88mm bore. If the top speed is 3°/s, the calculator gives an acceleration about 8°/s², so the acceleration time would be 0.38 seconds. The game shows 0.03 seconds.
![image](https://github.com/user-attachments/assets/c7209faf-91b9-431a-8689-c8e88c20184a)
![image](https://github.com/user-attachments/assets/01ec5cb5-c852-4343-a8f5-46827e8da96b)
