### ISSUE TITLE
Torque curve of engines has a shape closer to that of an HP curve

### ISSUE THREAD

**Issue by A1ex-Andro** [Muushy/Sprocket-Feedback#331]
This is what a torque curve usually looks like (Ford GAA):
![Ford GAA Torque Curve](https://user-images.githubusercontent.com/109421040/221364312-a8c04d1b-42ae-4134-af01-cab29d626c20.png)

**Comment by Muushy** [comment]
Increased curvature of curve in V0.1252.

**Comment by Muushy** [comment]
This is what's used in V0.1252:
<img width="943" alt="hcF8qFGRqm" src="https://user-images.githubusercontent.com/46500242/222189722-9e037a33-6bfb-4442-abef-b0353641f4ff.png">

The axes are normalized for the max torque (vertical) and max safe RPM (horizontal).
