### ISSUE TITLE
Power preview doesn't take into account engine torque curve

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#340]
Title, it calculated based off of the engines max torque instead of the torque produced at the set RPM

Image shows ~830nm at ~2200RPM (this is the limit) (graph seems to show lower than it actually is)

![image](https://user-images.githubusercontent.com/109303520/222083772-22c9b80b-422c-4f33-8101-4976f2386157.png)
![image](https://user-images.githubusercontent.com/109303520/222083826-939e79e2-bff6-48f0-8f68-bcbeff46a966.png)

Power shown in the UI:
![image](https://user-images.githubusercontent.com/109303520/222084088-8342539d-1b5e-4471-b244-e1305b621aec.png)

Actual power: 
![image](https://user-images.githubusercontent.com/109303520/222084481-20088142-487f-428c-b433-78fda5b94394.png)
I am aware this is metric horsepower and not imperial horsepower like in the game, but the difference wouldn't be anywhere near 100hp.

 Power calculated with 1160nm (max torque shown in the UI):
![image](https://user-images.githubusercontent.com/109303520/222085423-084bcc80-c018-4635-9225-9b0238d1d659.png)

**Comment by Muushy** [comment]
Fixed in V0.1252.
