### ISSUE TITLE
Speed in low gears does not match engine rpm (significantly higher than it should be)

### ISSUE THREAD

**Issue by A1ex-Andro** [Muushy/Sprocket-Feedback#346]
The top speed calculation in the designer is correct. However, if you set the highest gear such that the tank should top out at 10 km/h, it somehow manages to hit 14-15 km/h instead, at the rev limit. 

I noticed the following:
- With the same limit of 10 km/h (gear ratio and rpm adjusted of course), the tank instead hits 14 km/h with a small engine but almost 17 km/h with a very large engine.
- This difference between the correct speed at a given rpm and the actual speed also increases as you make the tank much heavier.
- Oddly, the suspension and roadwheel diameter appear to have a significant effect on it as well.
- The speed difference becomes more noticeable the lower the speed limit (ie, when you make a large top gear to set the speed limit to 1 km/h but the tank goes 7 km/h instead, you will notice).

I hope this helps you find the bug.

**Comment by Muushy** [comment]
Looks like the same issue as #321

**Comment by Muushy** [comment]
Fixed in V0.1253.
