### ISSUE TITLE
Tank auto steering on uneven terrain

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#349]
Title, very reminiscent of how it was when the game first released, but much less prominent, it is worse than it was in semi-recent updates, don't know how long it may have been going on (possibly related to reduced roadwheel simulation weight changes a little while ago?).

**Comment by Muushy** [comment]
Yeah it was due to the wheel collision position change in V0.1252.
Reverted back to how it was before in V0.1253.
