### ISSUE TITLE
Enemies in sandbox don't despawn when spawning another enemy tank

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#351]
Title, to reproduce simply press Z, spawn a tank, press Z again and spawn another tank.
The tanks don't despawn even if they're dead, the only way to get rid of them is returning to the designer.
Only the most recently spawned one has functional AI.

![image](https://user-images.githubusercontent.com/109303520/224201493-27875665-4d03-41b7-8a03-509ef22739a8.png)

**Comment by Tango0ps** [comment]
Pretty sure this is an intended feature.

**Comment by Muushy** [comment]
Fixed in V0.1258.
