### ISSUE TITLE
Broken RPM limiter slider

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#352]
The RPM limiter slider breaks when loading this tank for unknown reasons, loading another tank after this doesn't fix it.
The slider is moveable but it doesn't actually do anything.
It might be worth mentioning, I've had issues with this tank not saving the RPM limiter setting and getting reset to default upon game restarts.

[BM-5A.zip](https://github.com/Muushy/Sprocket-Feedback/files/10937731/BM-5A.zip)

**Comment by Muushy** [comment]
Should be fixed in V0.1253.
