### ISSUE TITLE
AI fails to do anything in Custom Battles (Basically braindead)

### ISSUE THREAD

**Issue by Tango0ps** [Muushy/Sprocket-Feedback#356]
**Describe the bug**

When creating a custom battle, tanks controlled by AI do not do anything and sit idly. They do not make any attempt to advance or even move their turrets. This sometimes applies to all tanks, or affects all except a few. This also seemingly happens for enemy AI, but upon getting closer they act as normal and begin moving and engaging. I cannot tell if the former applies for Friendly AI, or if its simply a waiting game, as later into the match some of them begin to move while others still remain idle.

This bug strangely does not apply to sandbox whatsoever and AI plays as usual.

**Version**
V 0.1252 Experimental

https://user-images.githubusercontent.com/83604390/224524842-22de3962-edcb-475a-8091-e0cad05456ca.mp4

**To Reproduce**
1. Create a custom battle on railway, clear clouds and no fog. Budget set to unlimited and players attacking.
2. Add up to at least 12 tanks for each team (Could work for more or less, but I am describing exactly what has happened)
3. Start the battle.

**Expected behavior**
I expected the battle to play out as normal, and the AI to move, target and engage as normal.

**Screenshots**
Video is attached.

**Additional context**
I believe I have been experiencing this bug since V0.12419 Experimental, but possibly earlier.

**Comment by Muushy** [comment]
AIs set to automatically attack in V0.1253.
The original idea was to lead them into battle with formations.
