### ISSUE TITLE
Empty text boxes say "Cannon" instead of "Name"

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#357]
Title.

To reproduce, get an empty part name text box anywhere, go to the cannon tab, and then return to the empty text box.

Going to the ammo tab makes all the text boxes say _Name_ instead.

![image](https://user-images.githubusercontent.com/109303520/224530830-5c24e6bd-5eb8-4b72-981f-cc4e9bdddec3.png)

**Comment by Muushy** [comment]
Fixed in V0.1258.
