### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by Hawker1775** [Muushy/Sprocket-Feedback#359]
**Describe the bug**
Black screen after launching the game.

**Version**
0.12423

**Additional context**
Black screen on startup. The mouse cursor is visible and can be moved. Background sounds are heard as if the game was running. If you press any key the game does not respond.

P.S. My lap top DELL Latitude E5530 Satisfies all requirements except the processor. I have not 3.3 but 2.6 GHz.

**Comment by Muushy** [comment]
The Intel HD Graphics 4000 graphics chip doesn't pass the minimum requirements.
It's simply not capable of running the game, it would be best to get a refund for now.
Sorry about that

**Comment by Hawker1775** [comment]
Nothing, I'll wait until the game is optimized or I'll buy a new laptop. Thank you for such an awesome game.
