### ISSUE TITLE
Extremely jerky gear shifting with clutch braking

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#360]
Title, it seems to slowly switch through every gear, accelerating, hitting the limiter, and then driving like that for a bit, and then finally switching gears.

But, with twin transmission, it switches through the gears effortlessly and smoothly compared to clutch braking.

**Comment by Muushy** [comment]
Is this fixed in V0.1254? Seems OK to me

**Comment by DarioXN** [comment]
> Is this fixed in V0.1254? Seems OK to me

Yup, it's fine now, opened this issue before it got fixed.

**Comment by Muushy** [comment]
Cool, thanks Dario
