### ISSUE TITLE
Turrets non-stop playing the turret rotation sound

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#365]
Title, doesn't always happen but it's pretty common.

**Comment by Muushy** [comment]
Fixed in V0.1258.

**Comment by DarioXN** [comment]
This one still seems to happen, it stops when aim lock is turned on, but still plays if it's off and the turret has rotated to where the player is aiming, and the turret no longer moving.

**Comment by DarioXN** [comment]
This one still seems to happen, it stops when aim lock is turned on, but still plays if it's off and the turret has rotated to where the player is aiming, and the turret no longer moving.

**Comment by Muushy** [comment]
Fixed in V0.1261.
