### ISSUE TITLE
Loading old part blueprints doesn't work

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#366]
Trying to load an old part blueprint (ex. cannon) doesn't work in 0.125, it seems to have worked in 0.124 and earlier.
Seems to happen to other parts, like the engine etc.

Old gun blueprint:
[HVEX-110_M87a3.zip](https://github.com/Muushy/Sprocket-Feedback/files/11006811/HVEX-110_M87a3.zip)

**Comment by Muushy** [comment]
Fixed in V0.1258.
