### ISSUE TITLE
T10 vent, Hetzer Exhaust, and Chi He driver port dont mirror model properly

### ISSUE THREAD

**Issue by Rhineland14** [Muushy/Sprocket-Feedback#375]
**Describe the bug**
When mirroring the models of the T10 vent and the Chi He driver port, they dont make the second model extrude the model in the reverse direction

**Version**
0.126 experimental

**To Reproduce**
1. Get part
2. mirror
3. put on tank

**Expected behavior**
Expected the models to flip like the american side exhaust

**Screenshots**

![20230325152507_1](https://user-images.githubusercontent.com/127696444/227737497-c4da7c73-d7d0-4da0-aaa5-975c88cfa784.jpg)
![20230325152749_1](https://user-images.githubusercontent.com/127696444/227737501-31448812-5373-4d1b-a7fb-fe8ff45d67e4.jpg)

**Comment by DarioXN** [comment]
The viewport isn't intended to flip, the vent and exhaust can be flipped by selecting them and ticking the box, works for certain other parts as well I believe:
![image](https://user-images.githubusercontent.com/109303520/227745310-d6458d1a-54e0-4516-a583-c8c9fa482c51.png)

**Comment by Muushy** [comment]
Intentional. Turned auto-flipping off as I felt it often got in the way when placing the T-10 vent and Hetzer exhaust.
