### ISSUE TITLE
Italian fender collisions

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#377]
The collision box for the Italian fender front piece (possible mid piece as well) is far in-front of the model.

Leading to floating tanks if the fender is angled downwards.
![image](https://user-images.githubusercontent.com/109303520/227745041-90820a8f-48d0-4b4d-aa79-58a74e13ad08.png)

**Comment by Muushy** [comment]
Fixed in V0.1261.
