### ISSUE TITLE
Item Duplication on Transform

### ISSUE THREAD

**Issue by SprangySprang04** [Muushy/Sprocket-Feedback#380]
This bug occurs randomly when translating, rotating, or scaling various parts, usually decoration and other parts from the Crew tab. What happens is that upon selecting the item or prop and transforming using the gizmos, the item creates a copy of itself when you click on the gizmo. It also sometimes happens when you left-click on the item to move it.

Version: V0.1261

1. Open Sprocket
2. Design a tank for about 20-30 minutes or more
3. Randomly have duplication bug
It's not very consistent to reproduce this bug, but it happens almost every time I design a tank.

Expected Behavior: Transforming an item does not duplicate it

Screenshots: As I said in the steps, it is not very consistent to reproduce this bug, so I don't have any screenshots of it, nor can I take any at the moment.

This bug may be related to another bug that randomly happens when picking up an item, right-clicking to remove it, but the item in question gets placed somewhere near the tank, usually floating in the air to the side or clipping inside of the tank.

**Comment by Muushy** [comment]
Duplication when performing a transform action is done while holding ALT.
It's likely your ALT key got stuck after tabbing out of the game, so it was doing it every time.
