### ISSUE TITLE
Track wrapping issues in newer versions

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#382]
Tracks don't wrap around the wheels properly (in this case the sprocket (file edited to another wheel)), don't know if it happens with other wheels, didn't happen before.

Example:
![image](https://user-images.githubusercontent.com/109303520/234402000-a02bf9c7-da57-426c-adba-3737dbb58260.png)

**Comment by Muushy** [comment]
Fixed in 0.2.6
