### ISSUE TITLE
See-through tracks while driving

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#383]
Title.

To reproduce:

- Go to any tab (tested in crew tab)
- Select the armour view
- Go to the compartments tab
- Spawn the tank

Example:
![image](https://user-images.githubusercontent.com/109303520/234402949-86299529-25bb-45f7-a4c3-8be8e8bc53ca.png)

**Comment by Muushy** [comment]
System rewritten in 0.2
