### ISSUE TITLE
wrong geometry values on loading

### ISSUE THREAD

**Issue by MeatLoafWellDone** [Muushy/Sprocket-Feedback#387]
After loading an existing blueprint the values for generated Hull.Front.Split and Hull.Rear.Split are beeing loaded with false values. In my case they were .30 m and loaded with .60 m generating a wrong (disfigured) geometry. I'm not sure when and how this happens, it has been a day since the design and loading of that blueprint, with a restart of my PC. Perhaps they have have been overwritten by the Hull.General.LowerHeight value.

V0.127

![20230428194437_1](https://user-images.githubusercontent.com/106024968/235217768-25e310cd-a994-46d2-9ab7-2bb9f8ea6f64.jpg)
![20230428194448_1](https://user-images.githubusercontent.com/106024968/235217785-10677172-9482-4b35-b1ea-d820335d7a10.jpg)

The cannon has been altered by me.

Best regards!

**Comment by Muushy** [comment]
Thanks for the report!
Fixed in 0.2
