### ISSUE TITLE
Flipping generated fenders

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#388]
It is possible to flip generated fenders, but upon saving and re-loading the tank, they flip themselves back to their original state.

![image](https://user-images.githubusercontent.com/109303520/236122382-8d4a23f5-53c8-4734-98b7-c335da24e74d.png)

**Comment by Muushy** [comment]
Flipping shouldn't be inconsistent in 0.2 anymore.
