### ISSUE TITLE
Typing in a large transmission gear count softlocks the game

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#392]
**Describe the bug**
Typing in a large gear count into the gear count slider (this specifically)
![image](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/ad045821-0757-4519-9d65-3b4804470a49)
locks the mouse to only being able to interact with the game UI, making you unable to interact with your tank or rotate/zoom the camera.  The bug persists until you load a new vehicle and re-type a small value into the gear count.

**Version**
0.127

**To Reproduce**
1. Go to the transmission tab while in latewar
2. Click on the text displaying the number of gears
3. Type in a really big number and hit enter.  This bug only works if you have to scroll to see all the gears after hitting enter.

**Expected behavior**
The game is not supposed to softlock when typing into the transmission gear count.  Strangely, this bug does not occur when clicking the + symbol to get the same gear count.

**Additional context**
I'm playing on an Ultrawide monitor, which may contribute to making the issue easier to run into.

**Comment by Muushy** [comment]
Fixed in 0.2
