### ISSUE TITLE
Track link spacing incorrect when first loading tank

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#393]
The spacing of track links on tanks is incorrect when making a new design (and possibly other instances).

To reproduce:
Click the new design button and it should happen.

They aren't even connected in this image, making the holes for the track pins visible:
![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/9a98d033-b420-413c-af7c-ec6dd700c48d)

Adjusting the track link length fixes it:
![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/a4d4e1c6-cc3e-49e5-8c93-0591990af6c3)

**Comment by Muushy** [comment]
Fixed in 0.2
