### ISSUE TITLE
Having loaders assigned breaks game when spawning tank

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#394]
Title, UI breaks, going back to main menu can fix it 

Logs
[Player.log](https://github.com/Muushy/Sprocket-Feedback/files/12315411/Player.log)
[Player-prev.log](https://github.com/Muushy/Sprocket-Feedback/files/12315412/Player-prev.log)

**Comment by SprocketTools** [comment]
Error is reproducible if ammo racks exist in different compartment than a gun resides in.

- turret gun + turret ammo works
- hull gun + hull ammo works
- turret gun + hull ammo + turret ammo softlocks
- turret gun + hull gun + turret ammo + hull ammo softlocks

Solution is to make sure all cannons and ammo racks are in the same compartment.

**Comment by Muushy** [comment]
Fixed in V0.2 CBT 2
