### ISSUE TITLE
Turret traverse motor statistics don't update in real time 

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#402]
Title.

![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/6bb06011-240e-4f7a-9218-dd6a261ea850)

**Comment by SprocketTools** [comment]
I think Hamish is aware of this bug, see the beta test notes:
`The initial test build wont include the following:`
`- Laying drive and traverse motor scaling with torque`

**Comment by DarioXN** [comment]
> I think Hamish is aware of this bug, see the beta test notes: `The initial test build wont include the following:` `- Laying drive and traverse motor scaling with torque`

That refers to the physical scale, the problem here isn't that it doesn't work, but that the UI doesn't update in real-time

**Comment by Muushy** [comment]
Fixed in 0.2 Closed-Alpha B0
