### ISSUE TITLE
Parts considered valid when moved entirely into another compartment

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#404]
**Describe the bug**
Title.  No collision flags appear when the engine collides with the turret basket.

![image](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/01b49c21-1b25-4bb1-96b7-d0dbf62f6469)

**Comment by Muushy** [comment]
The turret basket obstructs the drive shaft in 0.2 Closed-Alpha B0, stopping this from being valid.
