### ISSUE TITLE
Gun shields don't move with the gun

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#411]
Title.

![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/1df1db39-2294-4a54-ad7e-4e103a74dd8b)

**Comment by SprocketTools** [comment]
This issue was not prevalent with the original build, but I started noticing it in build #2

**Comment by SprocketTools** [comment]
Additional note: this issue only occurs after you load a saved design.  Vehicles being built from scratch do not have this issue.

**Comment by Muushy** [comment]
Fixed in 0.2 Closed-Alpha B0
