### ISSUE TITLE
Guns can fire even if there isn't any ammo of their type in the tank

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#412]
Title, guns can fire if the tank doesn't have their ammo, but does have ammo of another type.

Example, the small gun in the turret can fire even though it does not have any ammo, the only ammo present is for the big gun.
![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/eef09b99-91e4-4cfe-ad4e-44bb3b4a0664)

**Comment by Muushy** [comment]
System rewritten in V0.2 Closed-Alpha
