### ISSUE TITLE
Rotating the hull via file editing parameters rotates the whole tank

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#413]
My assumption is this is probably not supposed to be possible.  Changing these settings in the .blueprint for the hull physically manipulates the tank:

  "objects": [
    {
      "guid": "2fad78b46795d8f4ba04d2daf7e6bb9c",
      "vuid": 0,
      "pvuid": -1,
      "transform": {
        "pos": [
          0.0,              <<< these settings translate the tank's starting position
          2.0,              <<< these settings translate the tank's starting position
          0.0              <<< these settings translate the tank's starting position
        ],
        "rot": [
          180.0,              <<< these settings rotate the tank's starting position
          0.0,              <<< these settings rotate the tank's starting position
          0.0,              <<< these settings rotate the tank's starting position
          2.0
        ],
        

https://github.com/Muushy/Sprocket-Feedback/assets/137387488/8fc42876-b090-4931-94c1-2be493677af0

**Comment by Muushy** [comment]
Not an issue, just don't touch it
