### ISSUE TITLE
ricochet bug

### ISSUE THREAD

**Issue by enricfur** [Muushy/Sprocket-Feedback#419]
**Describe the bug**
When i shoot at angled plate, the projectile ricochets into the lower plate and it says that the angle is 29, but it is not true

**Version**
0.127

**To Reproduce**
You can use these two tanks to reproduce this shot:

[Vehicles.zip](https://github.com/Muushy/Sprocket-Feedback/files/12570727/Vehicles.zip)

**Expected behavior**
I expect the angle to be right

**Screenshots**
![изображение](https://github.com/Muushy/Sprocket-Feedback/assets/103355441/f9dc7982-089f-45de-b3f4-e3f6a34ea991)

![изображение](https://github.com/Muushy/Sprocket-Feedback/assets/103355441/881cb878-dd60-4481-866e-3c5ced40b6f5)

![изображение](https://github.com/Muushy/Sprocket-Feedback/assets/103355441/68dc5d29-7851-4359-be38-3b3cf861325f)

![изображение](https://github.com/Muushy/Sprocket-Feedback/assets/103355441/65b01f28-c386-48eb-92c9-062fd0277efd)

**Comment by Muushy** [comment]
Damage model rewritten in V0.2.
