### ISSUE TITLE
Muzzle brakes only point forward when loaded

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#421]
Placing a compartment sideways/backwards causes muzzle brakes to point the wrong way.  They point forwards when loaded.  This is only visible after reloading a design.

![2023-11-14_01-39](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/4031c34b-8fe9-445d-8621-062e3d421410)

![2023-11-14_01-36](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/266539dc-7d14-4bb0-8daa-c3b577beb050)

**Comment by Muushy** [comment]
Fixed in V0.2 Closed-Alpha B0
