### ISSUE TITLE
Mirrored objects will flip randomly when moved

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#425]
**Describe the bug**
Moving a part along a surface will cause it to flip randomly.  

https://github.com/Muushy/Sprocket-Feedback/assets/137387488/9eed9e55-8fc1-4bd9-b098-1190e60ead85

**Version**
0.2 CB

**Comment by Muushy** [comment]
Fixed in V0.2 Closed-Alpha B0
