### ISSUE TITLE
Objects attached to placeable fenders will mirror on each other, not the center of the compartment

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#426]
**Describe the bug**
When placing objects onto placeable fenders, they will mirror along the fender's origin instead of the vehicle's origin.
![image](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/83f5c149-85c9-4e91-9797-022a2e92987a)
![image](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/ddc3960c-a859-4790-b608-7fb4a075f24d)

**Version**
0.2 CB

**Comment by Muushy** [comment]
Fixed in 0.2.3
