### ISSUE TITLE
AI ignores player on Fields scenario

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#429]
**Describe the bug**
Player gets ignored by enemy AI on the fields map.  Only other AI tanks will be shot at.

**Version**
V0.127

https://github.com/Muushy/Sprocket-Feedback/assets/137387488/636345b2-3bc7-4a8e-a708-de9ab8c5eb27

**Comment by Muushy** [comment]
AI detection reworked in 0.2, should be fixed.
