### ISSUE TITLE
Assignment of limbs is not consistent

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#436]
**Describe the bug**
Rotating the cannon traverse and aiming the gun count as full-body tasks, when they should not.

**Version**
V0.2 0B

![image](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/2e253ba5-8c4b-4b20-bfd2-91e56b1fbade)

**Comment by Muushy** [comment]
Turns out limb assignment is working fine.
There's a hidden distance limit between roles. 
Moving the traverse drive closer to the laying drive would fix this.
Adding a visualization for the distance limit in B1.

**Comment by Muushy** [comment]
Limb assignment distance limits have been disabled
