### ISSUE TITLE
Mirroring on transmissions does not properly move everything in one direction

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#437]
**Describe the bug**
Transmission mirroring does not work properly.

**Version**
0.2 B0

https://github.com/Muushy/Sprocket-Feedback/assets/137387488/ba7d0ff3-fcdf-4d17-9373-c017e5a59270

**Comment by DarioXN** [comment]
This happens when mirroring is turned off

**Comment by Muushy** [comment]
Dupe of #445
