### ISSUE TITLE
Game does not switch back to external view when testing a tank

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#438]
**Describe the bug**
Game stays in internals view when testing if set to that when starting

**Version**
V0.2 B0

![2024-03-30_12-30-48](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/37527a85-1226-4c97-acd2-a6bdad87f0e1)

**Comment by Muushy** [comment]
Fixed in 0.2-CA-B2
