### ISSUE TITLE
Save UI does not block the selection of objects behind the window

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#439]
When you go to save a tank and click on the "Yes" button, something behind the vehicle will likely get selected and may not appear when reloaded.

**Comment by Muushy** [comment]
Can't seem to reproduce this.
Any luck @DarioXN?

**Comment by Muushy** [comment]
Nvm just got it

**Comment by Muushy** [comment]
Fixed in V0.2 Closed Alpha B1
