### ISSUE TITLE
Shadows do not cast correctly

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#440]
**Describe the bug**
See video

**Version**
V0.2 B0

https://github.com/Muushy/Sprocket-Feedback/assets/137387488/c3d5a21d-08d3-4859-be8e-4d00f9a2b257

**Comment by DarioXN** [comment]
The shadow model for the door on the square split hatch is offset.
Visible only in this view.
![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/66cdbf29-dee8-4206-a1d8-f495a170bf3f)
![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/cc262dcf-01e2-4796-8eb7-ebce924adf95)

**Comment by Muushy** [comment]
Fixed in 0.2-CA-B4
