### ISSUE TITLE
Reload speed is inaccurate

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#442]
**Describe the bug**
Reload speed is much longer than it should be

**Version**
V0.2 B0

**Steps to reproduce:**
- equip a large 105mm cannon
- assign one person to just load the vehicle

![2024-03-30_13-59-55](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/d05f8c42-daf2-4d01-9e95-0c567995e140)
![2024-03-30_14-00-13](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/c1123104-5f94-46d8-bc29-87f427193a10)

**Comment by Muushy** [comment]
Fixed in 0.2.2
