### ISSUE TITLE
Freeform scaling does not preserve ratios

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#446]
**Describe the bug**

https://github.com/Muushy/Sprocket-Feedback/assets/137387488/baf2dbd5-0988-4a89-ad60-cc7f161cd6b3

**Version**
V0.2 B0

**Comment by DarioXN** [comment]
This happens when mirroring is turned on

**Comment by Muushy** [comment]
Fixed in 0.2-CA-B3
