### ISSUE TITLE
Returning to the designer while in the sniper view doesn't leave the sniper view

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#448]
Title.
Spawning the tank after this hard locks the game.
![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/ef776959-2f7d-4e1d-95b8-94a36a28a58b)

**Comment by SprocketTools** [comment]
The sniper view actually works for you?  I haven't been able to get it working myself.

**Comment by Muushy** [comment]
Fixed in V0.2 Closed Alpha B1

**Comment by Muushy** [comment]
> The sniper view actually works for you? I haven't been able to get it working myself.

Not at all?
Should auto-assign a scope when you spawn. Multiple cannons will let you explicitly assign one.
Might be worth opening an issue.

**Comment by DarioXN** [comment]
I have not seen scopes be auto-assigned at all
