### ISSUE TITLE
Scaling issues with cupolas

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#462]
The two cupolas in the image have their hatch part move away from where it's supposed to be when scaled up or down, all the others are unaffected.

![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/8e272e7e-f079-43e7-80f0-9aaf33eb220e)

**Comment by Muushy** [comment]
Fixed in V0.2 Closed Alpha B1
