### ISSUE TITLE
Change drivetrain color to be unpainted

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#463]
Changing the color of the drivetrain to not be painted blue, if feels out of place since they are the only objects that are color coded in any way, everything else is normal.

![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/915c679f-0354-4560-9fc9-94ce5f94362c)

**Comment by Muushy** [comment]
Testing out unpainted in V0.2 Closed Alpha B1
