### ISSUE TITLE
Powertrain splitters have inverted collisions, causing beams to collide with each other.

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#466]
**Describe the bug**
This occurs regardless of positioning.
![image](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/9d0278a6-1d46-41e8-98f7-f35e47411c24)
![image](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/6c796e4c-d2aa-44d5-bebf-9914a58472a5)
![2024-03-30_23-26-25](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/74b02a75-d1a5-4a46-b9ad-1a492d1076d3)

Does not fix itself when reloading, or using another map
![image](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/861f5cac-a5f7-455f-90f9-e7d35138a6fb)

**Version**
V0.2 B0

**Comment by Muushy** [comment]
Any steps to reproduce this?
Can't seem to on my end.

**Comment by Muushy** [comment]
System rewrite in 0.2.3, probably fixed
