### ISSUE TITLE
High frequency camera jittering when driving

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#467]
Title, this is very noticeable if you zoom in close to your tank while the tank is moving, making it appear blurry.

**Comment by SprocketTools** [comment]
Tested with various graphics settings and it seems to only occur when DLSS is enabled.

**Comment by DarioXN** [comment]
> Tested with various graphics settings and it seems to only occur when DLSS is enabled.

I have AMD graphics, the DLSS setting is off and naturally doesn't do anything

**Comment by Muushy** [comment]
Fixed in V0.2 Closed Alpha B1
