### ISSUE TITLE
Paint projection not centered on the tank

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#468]
Title, it seems to be way in front of the tank, as seen when changing the paint scale and the warping in the circled area.

![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/24c9de9b-e6df-4d27-a678-85db9213756e)

**Comment by Muushy** [comment]
The paint is projected facing down and backwards at a slight angle to reduce distortion on the vehicle front.
This would offset the centre depending on vehicle height.
