### ISSUE TITLE
Poor shading on fuel tanks

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#469]
Title, this can be fixed by using weighted normals on the mesh and re-baking.

![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/fa4513ba-a33d-4393-b7b0-53140a1e095c)

Both cubes have same geometry
![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/1acbce44-b097-4497-91a4-c41199062013)

**Comment by Muushy** [comment]
Fixed in 0.2.1
