### ISSUE TITLE
Engine works when inside turret and gains the ability to transmit power wirelessly

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#473]
**Describe the bug**
Title
![2024-03-31_02-38-24](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/70ebd1a3-0e93-47c6-9750-f47043b5b540)

**Version**
V0.2 B0

**Comment by Muushy** [comment]
Any particular steps to stop that engine-transmission driveshaft from generating?
The driveshaft crossing the turret basket is generally what stops this from being valid.

**Comment by ColsonThePCMechanic** [comment]
Specific placement of the joints is usually necessary to achieve that.

**Comment by Muushy** [comment]
#485 is the culprit, no changes/constraints needed for engines.
