### ISSUE TITLE
Paint projection inverts based on scale

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#475]
**Describe the bug**
See pictures.

![2024-03-31_02-44-36](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/dfb6a2a9-52a8-4d29-94be-93a768d90856)

![2024-03-31_02-44-46](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/9ff008b3-5e00-4c88-9dbb-5b41a6115084)

**Version**
V0.2 B0

**Comment by DarioXN** [comment]
Likely related to #468

**Comment by Muushy** [comment]
Fixed in 0.2-CA-B2
