### ISSUE TITLE
High part count makes part selection inaccurate

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#477]
**Describe the bug**
Selecting anything just results in another crew member being selected.

**Version**
V0.2 B0

![2024-03-31_03-39-09](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/debca916-994a-415b-ab6d-1cb977bc68ca)

**Comment by Muushy** [comment]
Same issue as #540
