### ISSUE TITLE
Custom camouflages fail to load in situations of high crew member count

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#478]
**Describe the bug**
Title.
![2024-03-31_03-38-32](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/d8e170ed-a0e8-4c2c-8a94-2ece02f9dd79)

**Version**
V0.2 B0

**Comment by Muushy** [comment]
Potentially #452

**Comment by Muushy** [comment]
Haven't tested with the higher crewmembers but likely to be #452, which is fixed now.
