### ISSUE TITLE
Crew switching time indicator not functional when static crosshair is turned on

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#480]
Title.

![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/264c7a20-c2be-4c4d-a76f-9ae18d3ccdfe)

![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/71959ca9-b30c-4ee3-ab7a-1ccc25870a85)

**Comment by Muushy** [comment]
Fixed in 0.2-CA-B5
