### ISSUE TITLE
Front suspension getting stuck up

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#481]
At times one of the front wheels gets stuck in an up position, it still functions like this.

This happens after leaving the designer.
![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/9dd91f46-7068-4a09-af6c-88dd0bdc97e5)

**Comment by DarioXN** [comment]
I think it's worth adding that the suspensions generally feel weird, and torsion bar length and thickness doesn't really seem to do anything

**Comment by Muushy** [comment]
Suspensions should be fully reimplemented in 0.2.6
Was using the default spring torque value, which I'm guessing was the cause of the odd feel and front wheel being stuck up.
