### ISSUE TITLE
Armor is twice as heavy as it should be

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#483]
**Describe the bug**

Test sample 1: a 1x2x4m block on an otherwise stock vehicle.  Replicated in both 0.127 and and V0.2 B0
When the block was given 50mm armor:
Vehicle weight in 0.127: 17.86T
Vehicle weight in 0.2B: 25.4T

When the block was given 10mm armor:
Vehicle weight in 0.127: 9.09T
Vehicle weight in 0.2B: 7.82T

The difference in weight is roughly double.

Test sample 2: 
![image](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/faa4ff6b-3c15-4c64-93f2-dd10d8bf2b16)

**Version**
V0.2 B0

**Comment by DarioXN** [comment]
Slight correction, the weight is exactly double

**Comment by Muushy** [comment]
Armour volume calculation fixed in V0.2 Closed Alpha B1
