### ISSUE TITLE
Remnants of old drivetrain setup are left over when selecting transmission system

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#486]
Title, when you select the transmission system (currently only twin transmission), it resets the entire drivetrain back to default, but driveshafts still remain.

![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/59607269-201e-4cd9-804f-d0e43f1a00eb)

**Comment by Muushy** [comment]
Unfinished feature.
Powertrain selection disabled in 0.2-CA-B4 until it's fully implemented.
