### ISSUE TITLE
Interior of gun barrel has no shadows

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#487]
Title, while this would not be a problem in most cases, it does cause the shadow of the gun to have a hole in it under certain lighting angles.

![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/ad5d4393-a860-4834-a2a8-b3adb7196b91)

**Comment by Muushy** [comment]
Fixed in V0.2 Closed Beta B1
