### ISSUE TITLE
Loading blueprints fails on first launch

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#490]
**Describe the bug**
When opening the game and loading an existing blueprint, nothing will happen and the loading menu will be inaccessible afterwards.  Going to the main menu and reloading the map resolves the issue.

**Version**
V0.2 B1

**To Reproduce**
1. Open game
2. Open map
3. Try to load blueprint

Note: was also an issue in V0.2 B0

**Comment by Muushy** [comment]
Potentially fixed by #484
