### ISSUE TITLE
Update transmission scaling to have more consistent results

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#495]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/e7e517f3-3a65-43e5-87b1-9e5969216038)
Smaller engines and gear ratios often lead to pipe-shaped transmissions, which can also prove too long to fit into a vehicle.  Rearranging the powertrain is often mandatory when using more than 5 gears in order to make the transmissions fit.  

Another issue is that transmission sizes don't fully match up with how extreme their gear ratios are.  As an example, both of these transmissions have one gear that changes the rotation speed by a factor of 10, yet are significantly different in size:
![image](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/595624ab-d323-4212-aed0-6ca3e7b0769f)
![image](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/2f79e017-703e-44b0-858c-22d0d9294a4b)

This leads to engines with more displacement (and a lower RPM) being significantly better in minimizing transmission sizes, which doesn't align with how transmissions should be sized based on torque and internal gearing sizes.

**Describe the solution you'd like**
- Significantly increase the minimum width and height
- Make torque the primary factor in transmission diameter (but with slightly less effect compared to before)
- Only increase transmission diameter further if the gear ratios exceed a 10x difference between the smallest and biggest gear (ex: 5.0 --> 0.5 would not lead to a bigger transmission than a 3.0 --> 0.8 spread, while a 8.0 --> 0.6 spread would increase the diameter)

Not as critical, but may also be worth considering:
- Make transmissions shorter length-wise

**Comment by Muushy** [comment]
The current transmission size calculation is for the most simple type of transmission you can make. It's similar to the one on the T34. The size is calculated off of the physical gear sizes required to fit all ratios on one shaft, with two gears per ratio.

More advanced transmissions are planned to be available after WWI and the Interwar eras. These should fix the mentioned issues for higher gear count vehicles.
One which can engage multiple gears at once to form more ratios with the same number of wheels. Used on the Tiger I.
Another which uses a second transmission to exponentially increase the number of ratios created by the first. Used on the IS-2.

**Comment by ColsonThePCMechanic** [comment]
> The size is calculated off of the physical gear sizes required to fit all ratios on one shaft, with two gears per ratio.

There's still the issue of how ratios of 1:10 and 10:1 are treated differently, despite requiring the same gears.  Is there something I'm missing here?

**Comment by Muushy** [comment]
1:10 gets a vastly smaller transmission because the internal transmission shafts scale with the amount of torque they undergo.
1:10 means the countershaft can be much smaller (and closer to the input shaft) as it is receiving x0.1 the engine torque.
I'm no mechanical engineer and could certainly be wrong on this, but this is where my understanding of gearboxes is at.

The 1:10 transmission is a literal rod at the moment so that does need some work, might be worth a separate issue though.
