### ISSUE TITLE
Increased gun performance 

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#496]
Penetration on guns in higher than it was previously.
The velocity is the same so likely the K value is not being synced correctly.

Closed alpha version:
![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/a0979513-b8c1-437b-9f7c-65cbf5512c4a)

0.127
![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/32370738-bd38-4209-9d3d-49c38f819c31)

**Comment by Muushy** [comment]
Silly mistake using the mass of the projectile _and_ propellant to calculate penetration, instead of just the projectile.
Fixed in 0.2.11c
