### ISSUE TITLE
Placing mantlets causes instability when mirroring is turned on

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#503]
Title, to reproduce, have mirroring turned on, click on the mantlet part in the UI and then have it follow your cursor without placing it, then move your cursor over the center line of the tank.

![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/d4024a37-51ea-45f9-9a26-0bab8052acb3)

**Comment by Muushy** [comment]
Fixed in 0.2-CA-B3
