### ISSUE TITLE
Vehicles with no freeform shape crash the game

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#506]
Title, as in another issue, the game does not outright crash but becomes effectively locked.

To reproduce simply delete everything from the hull, and try to spawn the tank.
As far as I can tell, this is unrecoverable, meaning this tank at this point cannot be fixed (no way to re-add any plates).

**Comment by Muushy** [comment]
Fixed in 0.2-CA-B3
