### ISSUE TITLE
Lack of forwards projection on decals causes them to flicker when moving quickly

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#508]
Title, it's difficult to get an image of this, moving the decal forwards remedies the issue as it's bounding box is no longer so close to the surface it's placed on.

**Comment by SprocketTools** [comment]
Additional info: this bug is reproduced easily when exceeding 160km/h and you are looking down at the decal, like this.
![image](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/1fa4676f-ed94-4ae7-b40f-aa8d146aa570)
Stuttering became very noticeable here.

**Comment by Muushy** [comment]
Improved in 0.2.24.3
