### ISSUE TITLE
Splitting "inside" edges causes instability

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#509]
Splitting edges that have faces on both sides but would not form a full loop causes the game controls to lock up and saving the tank creates a broken save.

Splitting this edge would likely cause the issue.
![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/6190e35d-8bb0-4cd1-a4e6-e98e3ba67909)

**Comment by Muushy** [comment]
Fixed in 0.2-CA-B3

**Comment by DarioXN** [comment]
This one still happens in B3

**Comment by Muushy** [comment]
Haven't reproduced it in B3 yet.
Found any steps?

**Comment by DarioXN** [comment]
> Haven't reproduced it in B3 yet. Found any steps?

I had to try it a couple times but it did it when I tried to split this edge:
![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/61105200-a14d-4d8b-b72a-bbd5bbf08ed5)

**Comment by Muushy** [comment]
Nice one, got it

**Comment by Muushy** [comment]
Fixed in 0.2-CA-B4
