### ISSUE TITLE
Crew are (probably) still the same height as before

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#510]
Title, also even if not the case they are still too tall.

Previously they were roughly 186cm tall overall, and currently they seem to be about the same.

They should be about 170-175cm I've been told.

Image in current version:
![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/49b48e1a-1c54-42d0-8fa9-97959e40310d)

**Comment by Muushy** [comment]
Not really a bug.
They'll stay where they are until the upcoming crew posture rework.
