### ISSUE TITLE
Armor viewer colors solely based on angle

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#511]
Title, instead of effective armor, the colors in the armor viewer are influenced solely by angle.

![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/65d9e94b-639c-4468-b886-fbae3de7a0ee)
![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/4dd8f53c-b490-474a-b9ab-e64a27872c99)

**Comment by Muushy** [comment]
Thickness colour coding removed in 0.2.20
