### ISSUE TITLE
Wheels have extremely low weight

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#513]
Title.

Adding an extra wheel per axle on this adds only 20kg, for 12 more wheels total when counting the other side as well.
![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/deb6a9e9-ef5d-49f0-a8d5-3cbcd04b0e72)

**Comment by Muushy** [comment]
Fixed in 0.2-CA-B4
