### ISSUE TITLE
Adjusting crew posture with the armor viewer enabled makes the tank become purple

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#517]
Title.

To reproduce, turn the armor viewer on, and then play around with the crew settings.

![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/5ffd0207-9017-47f5-a4eb-54dd3448419c)

**Comment by Muushy** [comment]
Fixed in 0.2-CA-B4
