### ISSUE TITLE
Changing plate side textures for plates with no joints

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#519]
Changing the side texture of plates that are not connected to anything else to be like the top and bottom areas of the one in the example image instead of the current interlocking style.

![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/a6a9450f-4690-4fff-91e2-d11c6e760c28)

**Comment by Muushy** [comment]
Implemented in 0.2.4
