### ISSUE TITLE
Decal size sliders stop at 1000mm but max decal size is 5000mm

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#524]
Title.

![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/0d0601a8-dfa7-4136-8f2f-c88e29dc1439)

**Comment by Muushy** [comment]
Slider soft limit staying at 1000mm to preserve decent slider resolution.
Changing soft limits based on values input outside of the soft limits is something planned for the UI rework.
