### ISSUE TITLE
Purple wheels and muzzle brake

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#527]
Title, I can't reproduce this one because the game is behaving differently from when it happened, but here are the steps that caused it:

Load tank
Turn on interior view
Load another tank (either any tank or the one that loaded without paint like in #490 / #484 , don't know)

This is where I can't reproduce it, the game disables the interior view upon loading, but it didn't do that the time it happened, no relevant log files were generated.

![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/52a5e6e0-a640-4e94-82c9-a14d2bdbd42a)

**Comment by Muushy** [comment]
Asset loading saw a major iteration in 0.2.8. Likely fixes this.
