### ISSUE TITLE
Drive shafts vanishing upon leaving the designer

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#529]
Title.

It seems the center piece between the two transmissions doesn't care if it's blocked, and leaving the designer with the drivetrain set up like in the image causes certain parts of it to disappear.

![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/e98fcc42-c5f2-4ea6-97ef-67e7feabb9a9)

![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/e8b895c8-b700-43f1-bcc0-f292cfb5d989)

**Comment by Muushy** [comment]
Fixed in 0.2-CA-B5
