### ISSUE TITLE
Deleting edges leaves behind floating vertices

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#534]
Title.

There was an edge loop here and when I deleted it, this remained.

![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/efeb117c-55e9-455b-bca3-6b72c9b7de5a)

**Comment by Muushy** [comment]
Keeping this as a way to delete plates without deleting vertices
You can just select the loop, switch to the points tab and then delete to get the desired effect
