### ISSUE TITLE
Deleting edges can lock up the game

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#535]
Title.

When I deleted this edge, the game locked up.
![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/6109ca0f-afcb-4682-b461-54a35fafa17f)

Also happened with this.
![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/d0b7b751-3f25-4fa7-8df7-bc2759144bbb)

**Comment by Muushy** [comment]
Likely caused by mesh corrupted by edge splitting #509
