### ISSUE TITLE
Vertex thickness does not affect all connected faces

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#536]
Title.

One of the corners here is not affected:
![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/a3264b13-08d4-4f0c-88b4-e738de5fb249)

This is what the example looks like:
![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/f5b5a3ba-9305-4032-9f94-b1f411cd8cc3)

**Comment by Muushy** [comment]
Fixed in 0.2-CA-B5
