### ISSUE TITLE
Gun recoil does not reset for some parts when returning to the designer

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#539]
**Describe the bug**
![image](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/0cff33b3-b6ac-41e9-bee5-e82f8566243a)

**Version**
V0.2 B5

**To Reproduce**
1. Click to fire
2. Immediately return to designer with spacebar
3. See error

**Comment by Muushy** [comment]
Fixed in 0.2.1
