### ISSUE TITLE
Unable to select parts and crew

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#540]
This happens at random as far as I can tell, also seems to be a per tank thing, so reloading the tank or restarting the game doesn't fix it, the only way around it is to start over and hope it doesn't happen again.

This tank is affected:
[278.zip](https://github.com/Muushy/Sprocket-Feedback/files/14933249/278.zip)

**Comment by Muushy** [comment]
Fixed in 0.2-CA-B7
