### ISSUE TITLE
Loading screen is darker than intended

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#544]
**Expected look**
![2024-04-10_18-54-57](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/b093d12d-480d-4836-bbee-1c54af776976)

**Actual look**
![1674170_20240410185331_1](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/e8caf268-4693-4386-8115-6393f742f789)

**Game Version**
0.2.0

Note: screenshots were cropped differently.  Issue is the center of the video being too bright and washing out the background.

**Comment by Muushy** [comment]
Tweaked in 0.2.15
