### ISSUE TITLE
Extra drivetrain pieces appearing when loading a saved tank

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#547]
Title, don't know what causes it this time, they block other components.

![image](https://github.com/Muushy/Sprocket-Feedback/assets/109303520/1c905eb9-4cb5-4137-9873-efdb052dc107)

This tank has it happening, right in front of the engine, like in the image.
[290.zip](https://github.com/Muushy/Sprocket-Feedback/files/14945168/290.zip)

**Comment by Muushy** [comment]
Fixed in 0.2.1
