### ISSUE TITLE
FPS issues when loading a design with custom camouflague

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#549]
**Describe the bug**
Loading a tank with a custom camouflages will cause the game to stutter.  Opening the camo window causes the camo to then load, after which the stuttering goes away.

Example:
[XML-18.zip](https://github.com/Muushy/Sprocket-Feedback/files/14958958/XML-18.zip)

Camo name is "300-Series_Camouflage.jpg"
![300-Series_Camouflage](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/f8c3d5a9-1e16-4c79-bd4e-7adf618bbe71)

**Version**
0.2.1

**Comment by SprocketTools** [comment]
Found the issue.

Newer blueprints have color maps saved like this:
`"colourMapUrl": "file:///C:/Users/colson/Documents/My%20Games/Sprocket/Paint/300-Series_Camouflage.jpg",`
Old blueprints had it saved like this:
`"colourMapUrl": "C:\\Users\\colson\\Documents\\My Games\\Sprocket\\Paint\\300-Series_Camouflage.jpg",`

This bug has already been solved in newer game versions, by the looks of it.

**Comment by DarioXN** [comment]
Closed by request.
