### ISSUE TITLE
Armour Plates Intersect - Incorrect Weight

### ISSUE THREAD

**Issue by A1ex-Andro** [Muushy/Sprocket-Feedback#551]
**Version:** 0.22

1. Make a 1x1x1m cube out of a turret
2. Select all faces and set thickness to 500mm

**Expected:** 1 cubic metre of steel weighs 7850 kg
**Result:** Armour mass is 23550 kg

![Armour Cube 3](https://github.com/Muushy/Sprocket-Feedback/assets/109421040/dcc37877-3d69-4200-8ae7-74c7bf4f256a)
![Armour Cube 4](https://github.com/Muushy/Sprocket-Feedback/assets/109421040/bf5630de-e44f-4b43-81ca-1a5e70eb0fa7)

**Comment by Muushy** [comment]
Will unfortunately have to stay like this for now.
The plates need to overlap to preserve correct thickness and calculating the overlapping plate volumes isn't feasible.
