### ISSUE TITLE
Crew Member Becomes Amputee

### ISSUE THREAD

**Issue by A1ex-Andro** [Muushy/Sprocket-Feedback#552]
**Version:** 0.22

1. Set parameters as shown in screenshot (lower "sit height" and "feet forward" sliders).

![Crew 1](https://github.com/Muushy/Sprocket-Feedback/assets/109421040/73eb17dd-7f94-4dec-8f06-264cbdcd4ba3)

**Comment by A1ex-Andro** [comment]
![Crew 2](https://github.com/Muushy/Sprocket-Feedback/assets/109421040/b7be1455-8a6a-4df8-b502-7c3ef5b7b1ea)

**Comment by Muushy** [comment]
Crew posture system rewrite in 0.2.5
