### ISSUE TITLE
Crew Intersects Steering Wheel (but it is not necessary in the first place)

### ISSUE THREAD

**Issue by A1ex-Andro** [Muushy/Sprocket-Feedback#553]
**Version:** 0.22

Able to drive vehicle even while impaled by steering wheel (not that tanks use a steering wheel in the first place - a few examples do use one, _**but most used levers to steer the tank**_)

![Crew 3](https://github.com/Muushy/Sprocket-Feedback/assets/109421040/131c38bc-beb3-4e20-b57c-96ac1af6877f)

**Comment by Muushy** [comment]
Collisions don't seem necessary for a part purely there for role assignment.
Keeping a steering wheel for now as it's more recognizable to new players.
Levers may become an option later
