### ISSUE TITLE
Armour Not Joined Correctly in Generated-Mode Either

### ISSUE THREAD

**Issue by A1ex-Andro** [Muushy/Sprocket-Feedback#555]
**Version:** 0.22

As in the screenshots below, the front plate of the turret joins the cheek properly at the top, but not at the bottom. The armour values are likewise bugged.

![Armour Generated 1](https://github.com/Muushy/Sprocket-Feedback/assets/109421040/903f316a-92ba-4649-a2cc-d32528c83c80)
![Armour Generated 2](https://github.com/Muushy/Sprocket-Feedback/assets/109421040/715d089a-d255-4785-af4b-23d2b068dde9)
![Armour Generated 3](https://github.com/Muushy/Sprocket-Feedback/assets/109421040/7237a77a-8500-4a22-88c2-2b9a55a174af)

**Comment by Muushy** [comment]
Thickening prioritizes welded edges in 0.2.4, should fix that.
Also added tools to correct any issues manually.
