### ISSUE TITLE
Shells exploding immediately after firing

### ISSUE THREAD

**Issue by PuriPuriReek** [Muushy/Sprocket-Feedback#560]
Buged Steep Angle Dynamics and Open Tops being unable to shoot properly

**Version**
Current game version.
![20240412153437_1](https://github.com/Muushy/Sprocket-Feedback/assets/167028961/f3bdcd1a-8ff1-4896-93a0-50caf6029d84)
![20240414220440_1](https://github.com/Muushy/Sprocket-Feedback/assets/167028961/09703a71-b4b9-43bb-b1f7-d6512b56e796)
![20240414220441_1](https://github.com/Muushy/Sprocket-Feedback/assets/167028961/2e79978f-4108-4623-80e5-88458f7e9342)
![20240414220443_1](https://github.com/Muushy/Sprocket-Feedback/assets/167028961/4be80732-78a8-4a16-aa50-0065d98a7243)
![20240414220447_1](https://github.com/Muushy/Sprocket-Feedback/assets/167028961/7128fc7c-0559-4ade-b49e-43d953007b1d)
![20240414220518_1](https://github.com/Muushy/Sprocket-Feedback/assets/167028961/9726989b-9300-4265-8722-a79cb9608857)
![20240414220559_1](https://github.com/Muushy/Sprocket-Feedback/assets/167028961/f2951496-c095-4545-8aff-1b2aefc48dc0)
![20240414220608_1](https://github.com/Muushy/Sprocket-Feedback/assets/167028961/dffe38d1-ad09-43aa-9e15-a5420bd5ec91)

Bug 1: Vehicles are allowed to stand on absurd angles and even wall ride just kike moving on a flat surface (even 90 degrees) to acheve this you must press your forward key very fast and not thouching it again untill the vehicles stabilises

Bug 2: At very steep angles aiming from sights are replaced with camera rotation instead of pitching and yawing.

Bug 3: Mostly open top vehicles have issues shooting at degrees below positive 20 degrees. The bug couses bullets to explode mid air and often right after shooting aout of the barrel.

All are tested and supported with images.
Sprocket 2.2

**Comment by Muushy** [comment]
Bug 3 fixed in 0.2.8
