### ISSUE TITLE
Armor is often reported 1mm under its actual thickness

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#563]
**Describe the bug**
![image](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/64a1380e-86c9-40ac-9479-b961d83c07cb)
Screenshot is from <https://youtu.be/f6c9IF295lI?t=1246>.  I have observed this myself at least once already.

**Version**
0.2.2

**Comment by Muushy** [comment]
Armour thickness detection was iterated on in 0.2.8. Seems fixed at a glance.
