### ISSUE TITLE
Automatic era switching resets powertrain placement

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#569]
**Describe the bug**
File editing a vehicle to use an earlier era, then loading it, triggers the era conversion to Late WWII.  This causes the position of the powertrain components to reset.

**Version**
0.2.4

![2024-05-26_04-15-09](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/2f2f9d33-1afa-49ed-9411-7fbb1f9b5f19)

**Comment by Muushy** [comment]
Earlier eras are not reimplemented yet
