### ISSUE TITLE
Selecting track parts selects additional powertrain objects behind the cursor

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#572]
**Describe the bug**
![2024-06-12_02-36-31](https://github.com/Muushy/Sprocket-Feedback/assets/137387488/be56bec1-9da2-44d0-80e4-698397722a21)

**Version**
0.2.6

**To Reproduce**
1. Select the track belt
2. Select the engine block
3. Engine settings will appear in belt settings instead of opening the engine UI

**Comment by SprocketTools** [comment]
Note: this seems to also happen when selecting the belt, and then the transmission.  If you then go select something else, the transmission settings will persist after selecting that object.

**Comment by Muushy** [comment]
Fixed in 0.2.9

**Comment by Muushy** [comment]
Still present

**Comment by Muushy** [comment]
Fixed in 0.2.21
