### ISSUE TITLE
Compartments cannot be selected if multiple corners set to horizontal extrusion

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#579]
**Describe the bug**
After selecting multiple corners and setting them to horizontal, the compartment can no longer be selected and therefore cannot be edited, or have items placed onto it.

**Version**
0.2.7

**Additional context**
Multiple users have reported this problem.

**Comment by Muushy** [comment]
Fixed in 0.2.9
It's an issue with the horizontal thicken mode on faces facing perfectly downwards.
