### ISSUE TITLE
Cannot get past Unity Diagnostics screen on fresh game install

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#582]
**Describe the bug**
Title.  As reported by several users, a fresh install of the game will lead to a softlock when the Unity Diagnostics prompt appears.  

**Version**
0.2.8

**Comment by SprocketTools** [comment]
Solution found:


Open the Registry Editor

Go to `Computer\HKEY_CURRENT_USER\SOFTWARE\HD\Sprocket`

Open `DiagnosticsTogglePrompted_h1869189318`

Change the value to 1

Click "OK"

Launch the game

If this value is at 0, the game softlocks

**Comment by SprocketTools** [comment]
Further update: Alot of these reports are showing that Sprocket simply isn't creating the appropriate registry files in the registry editor.  One person said to run Sprocket as administrator.  We've been directing people to make these registry files themselves.

**Comment by Muushy** [comment]
Thanks, very useful!
A 0.2.8 change was preventing inputs from being read when this prompt appears.
Fixed in 0.2.9
