### ISSUE TITLE
Cannons cannot penetrate armor plates thicker than an unknown caliber-based value.

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#583]
**Describe the bug**
Tested on multiple cannon calibers and propellant lengths against a vertical armor face.  Any armor plate thicker than 96mm cannot be penetrated regardless of whether the cannon is stronger or not.

**Version**
0.2.8

**Comment by SprocketTools** [comment]
Update: the tests ran previously were with a 105mm+ caliber.  Now trying a 90mm cannon, and it is unable to pen more than 57mm of armor.

**Comment by DarioXN** [comment]
I think it might be pen drop-off over distance being bugged.

**Comment by Internetzspacezshipz** [comment]
User "IDK Anymore" on steam posts that the penetration values seem to be half what they should be - so on the weapon displaying 250mm pen, it will actually only pen 125mm, and if the weapon claims penenetration of 100mm, it will actually only pen 50mm.

 Link to message here: https://discord.com/channels/788349365466038283/879446071007379476/1266156765242982421

**Comment by Muushy** [comment]
One big cause was #592
Fixed in 0.2.11
