### ISSUE TITLE
Armour/armor (search visibility) plates are massless when having gradient armour thicknesses

### ISSUE THREAD

**Issue by Internetzspacezshipz** [Muushy/Sprocket-Feedback#585]
**Describe the bug**
Armour can be made massless or actually have NEGATIVE mass if any of the vertices or wedges in a face are set to have a different thickness value from the others in that face. See attached images.

**Version**
unknown creation version - possibly in first version with geometric internals.
0.2.8
0.2.9

**To Reproduce**
1. Select individual element of a plate on any of these modes:
a. vertex mode
b. edge mode
c. wedge mode
2. change armour thickness to be a value different from the other elements of that face
3. observe that armour now has lower mass, possibly even 0 mass. This can be subtracted from existing plates that do have correct mass (image 0 shows this well).

**Expected behavior**
Obviously armour mass should never be negative for any given plate, and it should be correctly calculated.

**Screenshots**

image 0 (armour has zero mass): ![image](https://github.com/user-attachments/assets/2018f601-516d-4d88-8c62-0d77996717e9)

image 1 (when armour has same thickness across all elements): ![image](https://github.com/user-attachments/assets/af410066-7691-4640-aad3-94e5fa0568da)
image 2 (single vertex different from other vertices thickness): ![image](https://github.com/user-attachments/assets/5ecf20e3-8271-4cde-96ca-be5b8bdac8a4)
image 3 (single wedge having different thickness from all other wedges): ![image](https://github.com/user-attachments/assets/e40557f5-8ff4-4081-a94d-f828b897b2a4)
image 4 (single wedge having different thickness from all other wedges, but translated toward camera. The further away face has half the mass it should have): ![image](https://github.com/user-attachments/assets/28ed4be4-d594-41cb-9abb-9fc142c8d567)
image 5 (single wedge having different thickness from all other wedges, but translated away from camera. The further away face has half the mass it should have, but the face closer to the camera has negative mass, which causes the whole armour part to be massless): ![image](https://github.com/user-attachments/assets/d40edc13-d559-4c74-9efb-c350be6fb74e)

**Additional context**
This occurs in any situation using armour plates, turrets, additional armor pieces, main hulls etc etc.
I am not certain whether this is just a UI bug (perhaps the armour masses are being calculated in different ways for the UI and the actual physics? Not sure, but I would assume they are the same).

**Comment by Muushy** [comment]
Fixed in 0.2.13
Thanks for the detailed rundown!
Also turns out that faces with uniform thickness were x2 heavier than they should have been.
