### ISSUE TITLE
Tank center of mass is determined by center of platform, instead of center of tank

### ISSUE THREAD

**Issue by robotnikthingy** [Muushy/Sprocket-Feedback#586]
**Describe the bug**
The center of mass on tanks is determined by their position on the tank platform rather than the center of the actual tank. This causes issues mostly for smaller vehicles if one ends up building their tank a little more forward or backward on the tank building platform

**Version**
0.2 Alpha

**To Reproduce**

**Expected behavior**
Center of mass should be center of tank

**Screenshots**
![image](https://github.com/user-attachments/assets/40ae2c60-52a0-48b5-b1e4-cf467af1298f)

**Additional context**
Zip file with tested blueprint
[Mark-259-test.zip](https://github.com/user-attachments/files/16355864/Mark-259-test.zip)

**Comment by DarioXN** [comment]
Same as #107
