### ISSUE TITLE
Sometimes crew members unselectable when opening the sandbox editor for the first time

### ISSUE THREAD

**Issue by Internetzspacezshipz** [Muushy/Sprocket-Feedback#587]
**Describe the bug**
When opening the game and then opening the sandbox, sometimes crew members, and possibly other components become unselectable until the vehicle is reopened. This only seems to occur when the sandbox automatically loads the last edited vehicle. I have attached a vehicle blueprint in case it is inconsistent. On this blueprint it always occurs for the crew member in the right hand side of the turret.

**Version**
Possibly earlier versions
0.2.9

**To Reproduce**
1. Open game
2. Open Sandbox (flat)
3. Mouse over each component
4. Sometimes a crew member (or possibly other components) might be unselectable

**Expected behavior**
All crew members and objects are selectable right away.

**Screenshots**
Image shows me attempting to select the crew member in the foreground, but instead the crew member behind is selected.
![image](https://github.com/user-attachments/assets/436425c0-2761-4779-9717-8db9b7987781)

**Additional context**
You can work around this issue by reloading the same blueprint again manually."

Attached blueprint which always has the issue occur if it is loaded automatically by the game: I
[XT89.zip](https://github.com/user-attachments/files/16356538/XT89.zip)
It will always occur to the right hand crew member in the turret when the game automatically loads this vehicle at startup.

**Comment by SprocketTools** [comment]
Ran into this as well, reloading the flat sandbox seemed to help it

**Comment by Internetzspacezshipz** [comment]
> Ran into this as well, reloading the flat sandbox seemed to help it

Yeah! It does have workarounds you can do to avoid it (such as reloading the relevant vehicle manually), but it can cause some frustration or confusion if one does not know why it is occurring.

Obviously it's not a hugely critical bug like that one with disappearing roadwheels though.

**Comment by Muushy** [comment]
Think this one was due to the 0.2.8 part loading bug as well.
Marking as fixed (0.2.10) for now.
