### ISSUE TITLE
Transmissions appear to go invisible when reducing the number of gears

### ISSUE THREAD

**Issue by Internetzspacezshipz** [Muushy/Sprocket-Feedback#588]
**Describe the bug**
When reducing the number of gears in the transmissions, the transmission inner sections disappear. They are correctly shown when loading a vehicle or making a new vehicle.

**Version**
0.2.9

**To Reproduce**
1. Enter sandbox
2. Create new vehicle
3. Reduce number of gears in the transmission

**Expected behavior**
The transmission should look normal after any and all operations done to it.

**Screenshots**
![image](https://github.com/user-attachments/assets/98dcfafc-da92-4b5c-a3d5-8a2f14b972e4)

**Additional context**
This could also be related to the [roadwheels disappearing bug](https://github.com/Muushy/Sprocket-Feedback/issues/584), although this one is much less severe since it does not block further modification or hitting the play button.

**Comment by DarioXN** [comment]
Similar thing happens to engines when reducing the amount of cylinders.

**Comment by Muushy** [comment]
Fixed in 0.2.10
