### ISSUE TITLE
Round Velocity being inconsistent.

### ISSUE THREAD

**Issue by Kuakster** [Muushy/Sprocket-Feedback#592]
**Describe the bug**
This bug is where the shells fired from two guns with wildly different muzzle velocities have both the same velocity and bullet drop rate. 
For example, a 20mm cannon firing a bullet at 1233m/s has the same bullet drop as a 90mm cannon firing a massive slug at 230m/s. Sometimes, it is the inverse. The phenomenon is incredibly unpredictable, and i cannot for certain tell when it is going to happen. 
The bug  seems to only affect vehicles that are near identical

**Version**
0.2.10b

**To Reproduce**
1. First take any vehicle and change its cannon so that the indicated muzzle velocity is far higher or far lower than the original.
2. Next, test drive the modified vehicle.
3. Fire the cannon of the modified vehicle.
4. Save, and then load the original vehicle, make sure to change the name of the modified vehicle so that the original does not get overwritten. 
5. Test drive the original vehicle and fire its gun, you will notice they have the exact same shell velocity and bullet drop. 
6. Error found

**Expected behavior**
When firing guns of wildly different velocities from nearly identical vehicles, they have the exact same apparent muzzle velocity and exact same bullet drop.

**Additional context**
Experiment conducted above was when the gun sight's horizontal line matched perfectly with the horizon from the stand from which the player tank spawns on.

**Comment by Muushy** [comment]
Yeah there's definitely a clear problem here.
Thanks for the report!

**Comment by Muushy** [comment]
**Fixed in 0.2.11**
Was an issue with vehicles not releasing correctly.
The first you exit the editor with would register its projectiles under an ID.
That ID wouldn't be released when returning to the editor so the next time the editor was exited, it would simply reuse the previously registered projectile instead of creating a new one with any updated changes.
