### ISSUE TITLE
Game stuck on loading screen when the last saved blueprint is corrupted

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#593]
**Describe the bug**
Blueprints are occasionally corrupted for still unknown reasons.  When they are corrupted and the map is reloaded, the game attempts to load the corrupted blueprint, but becomes stuck at the loading screen due to being unable to load the file.

**Version**
0.2.11

**To Reproduce**
1. Corrupt the last saved blueprint
2. Launch the game and open a map

**Comment by Muushy** [comment]
Anyone encountered this in 0.2.12 onwards?

**Comment by DarioXN** [comment]
> Anyone encountered this in 0.2.12 onwards?

Not to my knowledge.

**Comment by ColsonThePCMechanic** [comment]
This issue  has likely been reduced in frequency with the changes to how corrupted structures are loaded.

**Comment by Muushy** [comment]
Cool, will close for now
