### ISSUE TITLE
Changing the type of tracks when having a track spares does not update all track spares

### ISSUE THREAD

**Issue by Internetzspacezshipz** [Muushy/Sprocket-Feedback#594]
**Describe the bug**
When changing the type of tracks used and having spares on your vehicle that have been duplicated, only the initially placed track spares will udpate their type.

**Version**
0.2.11

**To Reproduce**
1. Place track spares
2. Duplicate track spares by holding alt and dragging one of the axis arrows.
3. Change types of tracks vehicle uses.
4. Only the first placed track spares will change type, while the other spare tracks will not

**Expected behavior**
Expected all track spares to update to the new selected track type.

**Screenshots**
![image](https://github.com/user-attachments/assets/09ecc7e1-62e1-4b03-92f0-9e7daaee173d)

**Additional context**
Reloading the vehicle does not solve the issue - the tracks will stay as the incorrect type despite reloading the vehicle. Requires placing of the track spares again to workaround.

**Comment by Muushy** [comment]
Fixed in 0.2.13
