### ISSUE TITLE
Sometimes components such as ammo rack seem invulnerable to shooting.

### ISSUE THREAD

**Issue by Internetzspacezshipz** [Muushy/Sprocket-Feedback#595]
**Describe the bug**
In some situations, shooting a vehicle's components seems to not work. I have attached a link to a video of me shooting through 50mm armour with a gun that has 300mm+ penetration into ammo racks and not detonating them:

video:
https://www.youtube.com/watch?v=-WKTWSd8cK4

vehicle file:
[XT111.zip](https://github.com/user-attachments/files/16462409/XT111.zip)

**Version**
0.2.11

**To Reproduce**
1. Start playing 
2. Fire at ammo racks
3. No explosion in some cases

**Expected behavior**
Ammo rack explodes when being shot once or multiple times

I have added the vehicle that I was using in this test to this post.

**Comment by Muushy** [comment]
Ammo racks wont detonate if their projectiles are hit, instead of their propellant. If the projectiles are hit, all shells in the rack are lost.
Keeping this open as it does need to be made clearer.

**Comment by Internetzspacezshipz** [comment]
That makes sense, however I am not sure if there might be a bug with it considering I shot the rear of the vehicle in that clip I posted many many times in different spots where the ammo was located and not once was there an ammo explosion... It's a bit difficult to tell exactly what is going on though. Hopefully we can get the penetration simulation stuff in a build soon so it's easier for players to test it!

**Comment by Muushy** [comment]
Likely fixed by 0.2.20
Once post-pen simulations reached a certain complexity, damage would no longer be applied.
