### ISSUE TITLE
When a turret is mounted to another turret at a 90 degree angle, aiming becomes unpredictable and glitchy.

### ISSUE THREAD

**Issue by Internetzspacezshipz** [Muushy/Sprocket-Feedback#597]
**Describe the bug**
When using either of the vehicles attached, the traverse and elevation of the gun becomes unpredictable, and is almost always stuck.
My assumption is that this could be due to euler angles being used, causing a gimbal lock situation, which then means the turrets cannot figure out which one should move in which direction. Of course, this is just my educated guess, considering I have no idea how the aiming code actually works!

Also, in addition to this, the bot tanks seem to be able to at least aim in one axis at their target.

**Version**
0.2.12

**To Reproduce**
1. Load one of the vehicle blueprints attached
2. Hit play
3. Attempt to aim the gun.
4. Turrets seem to be unable to move, although making the noise as if one of them is moving.

Making a new vehicle:
1. Create a vehicle
2. Attach turret
3. Attach another turret at a 90 degree angle about the vehicles lengthwise axis (roll axis when in the vehicle hull frame of reference)
4. Attach gun to the last turret
5. Add required crew members
6. Hit play and observe that the vehicle cannot aim 

Vehicle I originally found this issue with:
[XT115.zip](https://github.com/user-attachments/files/16485376/XT115.zip)
Test vehicle I created to ensure that it wasn't just on the first vehicle:
[XT116.zip](https://github.com/user-attachments/files/16485377/XT116.zip)

**Expected behavior**
I expect that the turrets should be able to figure out which direction to aim in, no matter the number of turrets that are attached to each other. I know that in the stable version of the game, putting turrets on turrets (including at a 90 degree angle)

**Comment by Muushy** [comment]
Oriented turret aiming fixed in 0.2.21
Had to add another crew member to have both turrets moving simultaneously, as gunners can currently only control one at a time. That's a separate issue though.
