### ISSUE TITLE
Renaming the vehicle without pressing 'enter' at the end leaves the internal state of the name as it previously was

### ISSUE THREAD

**Issue by Internetzspacezshipz** [Muushy/Sprocket-Feedback#599]
**Describe the bug**
When renaming a vehicle, then not pressing enter (clicking away from the text box to exit it), the UI text box appears to have the new name, but when you go to save it will ask to overwrite the old name. This leads me to believe that there are two states for this UI box: the UI one, and the logical one. When not pressing the enter key, it does not call the callback to update the logical name of the vehicle to the UI one. This is potentially an easy fix in one of two ways:
  Option A: reset the text in the text box if the user clicks out of the text box
  Option B: update the logical name with the text box's value when the user clicks out of the box
  Option C: remove copied state ( !! most optimal solution, since WYSIWYG !! ), opting for text box to directly edit and show logical state.

**Version**
2.12

**To Reproduce**
1. Create new vehicle
2. Save vehicle
3. Rename vehicle, but do not hit the enter key when finished renaming, instead click somewhere else to cause the text box to lose focus
4. Attempt to save vehicle, seeing that the game will ask for an overwrite. 
5. If you choose yes, it will overwrite the original vehicle name, not creating a new vehicle.

**Expected behavior**
Clicking away from the text box does not desynchronize the two states, so that it is consistent with hitting enter after editing the name.

**Screenshots**
Better, a video:
https://www.youtube.com/watch?v=Kve_MonARZI

**Additional context**
This bug has actually been around for a long time, so I assumed it had already been reported here, but it seems it has not!

This bug can definitely cause a lot of confusion and frustration, possibly destroying vehicle saves by accident.

**Comment by Muushy** [comment]
Thanks for the report!
Fixed in 0.2.20
The rename command, wasn't receiving the first change to the name.
Resulting in this happening if only a single character was added/changed.
