### ISSUE TITLE
Adding turrets crashes the game

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#600]
Title.

Upon adding a turret of any kind, leaving the designer and then returning to the designer, any attempt to leave the designer after this will cause the game to practically hard lock, leaving to the main menu will cause an infinite loading screen, and no part of the UI works.

Blueprint and log files: https://discord.com/channels/788349365466038283/1135007733175816282/1272863291672363068

It seems to only affect new tanks or turrets made in 0.2.13, old tanks or at least tanks with turrets placed in previous versions work fine.

**Comment by Muushy** [comment]
Fixed in 0.2.13e
