### ISSUE TITLE
Selection of addon structure sometimes is not possible

### ISSUE THREAD

**Issue by Internetzspacezshipz** [Muushy/Sprocket-Feedback#608]
**Describe the bug**
It seems when addon structures are comprised of a single plate and are attached to the gun barrel, they become impossible to select by clicking on them.

Check attached vehicle blueprint for easy reproduction.

**Version**
0.2.13 and earlier versions

**To Reproduce**
1. Add a additional armor structure to gun barrel
2. Delete all faces but one
3. Find that plate becomes impossible to select

**Expected behavior**
Plate should be selectable.

**Screenshots**
![image](https://github.com/user-attachments/assets/758cf737-9ac0-443c-8dcf-f89e78d4d416)

**Additional context**
[XT131.zip](https://github.com/user-attachments/files/16654765/XT131.zip)

**Comment by Internetzspacezshipz** [comment]
Assuming this is caused by an off-by-one error of some sort (since there is only a single face, it could be counted as 0 faces to the selection logic)

**Comment by Muushy** [comment]
The same issue as #662, fixed in 0.2.21.
