### ISSUE TITLE
Coordinates Origin

### ISSUE THREAD

**Issue by DutchDragonborn** [Muushy/Sprocket-Feedback#610]
As is now the case, the origin point (X,Y,Z - 0,0,0) for the ingame coordinates rests at the bottom center of the tank hull. This is undesirable for me as it makes several things more dificult in my opinion:
- determining the actual dimensions of the tank
- determining ground clearance, height of the gun bore, total height of the tank hull and turret
- acurately placing and moving points and parts in within negative coordinates
- actual height of sprocket wheel, return rollers and idler

I suggest moving the origin for all parts (hull, turret and tracks) on ground level (Z= actual 0), linked to the center of the rearmost point on the tank hull (X,Y = 0)

**Comment by Muushy** [comment]
It's more effort than it's worth.
There's plans for a vehicle summary generator, to automatically calculate much of this info for you.
