### ISSUE TITLE
Engine and transmission are selectable through hull and add their menu stuff to the right side of the screen

### ISSUE THREAD

**Issue by CSNelson7** [Muushy/Sprocket-Feedback#617]
![image_2024-08-29_160932608](https://github.com/user-attachments/assets/366f99c5-b60a-49ee-8f01-45f976b52c1f)

As described in the title. This is rather annoying when attempting to work on tracks because i keep accidently selecting the engine or transmission and having them interrupt my work.

**Comment by Muushy** [comment]
Dupe of #572
