### ISSUE TITLE
Ammo not duplicating properly

### ISSUE THREAD

**Issue by Raichor** [Muushy/Sprocket-Feedback#625]
**Describe the bug**
Duplicating ammo does not copy scale

**Version**
0.2.16b

**To Reproduce**
1. Place ammo
2. Resize
3. Click and hold alt to duplicate
4. Duplicated ammo is not the same scale/number of rounds

**Expected behavior**
Expected to copy scale properties of duplicated ammo

**Comment by Muushy** [comment]
Fixed in 0.2.21
