### ISSUE TITLE
Debug Mode

### ISSUE THREAD

**Issue by XenoHoe** [Muushy/Sprocket-Feedback#633]
With more and more file-editing possibilities being added, I tried playing around with it, and of course the new era and tech I added didn't work in game. That's where I got lost, because I didn't know what went wrong with the files. 

Sincerely hope there is a "debug mode" where we get to see the log output of the game, maybe activated by using steam launch arguments like "-debug", so we can at least diagnose which part went wrong in the files/game process rather than changing things around like headless flies hoping that something would work.

Can't really think of any alternatives at the moment.

**Comment by Muushy** [comment]
The logs at "%userprofile%\AppData\LocalLow\HD\Sprocket\Player.log" works fine for now.
May do this solution when mod support is in.
