### ISSUE TITLE
Eras do not properly apply drivetrain settings

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#634]
**Testing ran to find the issue**
I ran some tests between 0.127 and 0.2.18e, using an in-development version of https://sprockettools.github.io/TopGearCalculator.html to obtain expected performance values.
In both cases I used a midwar testbed with a 24L V6 engine, and a vehicle weight between 11.1T and 11.3T.

In 0.127 the vehicle reaches within 2km/h of its expected target of 78km/h
![2024-09-29_02-40-51](https://github.com/user-attachments/assets/2eec66a3-9963-44d6-8230-a8ef977d7a10)

In 0.2.18e the vehicle starts to stall when it shifts into 4th gear, unable to break 45km/h
![2024-09-29_02-44-47](https://github.com/user-attachments/assets/fc664618-c40f-4db0-a6ec-cd7ab72c9dd0)

**Version**
0.2.18e

**Additional context**
It's very likely that 0.2.18e is applying a singular value across all eras.  Others have reported that the calculator gives incredibly below average values with the interwar era, so it may be that a value from another era (such as earlywar) is being applied universally to everything.

**Comment by Muushy** [comment]
Can confirm rolling resistance tech isn't synced properly in 0.2.18e.

**Comment by Muushy** [comment]
Fixed in 0.2.19
