### ISSUE TITLE
Exhaust effects break once a vehicle begins playing

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#636]
**Describe the bug**
Start by opening a tank in the editor
![image](https://github.com/user-attachments/assets/671caa72-de92-46d7-9894-1536e564643c)
Once you hit "play" the exhaust effects turn off, except for their blur effect:
![image](https://github.com/user-attachments/assets/fdee85d9-f8d6-4d94-9149-f9a16f436b6e)
![image](https://github.com/user-attachments/assets/1235665a-2884-4511-93de-a665e2780c23)
The blur effect also hides when in the designer.
This persists until the vehicle is reloaded or has its era changed.

**Version**
0.2.18e

**Comment by Muushy** [comment]
Fixed in 0.2.20
