### ISSUE TITLE
Exhaust smoke in eras.

### ISSUE THREAD

**Issue by Harbisonel** [Muushy/Sprocket-Feedback#637]
**Describe the bug**
 In short: Exhaust smoke seems to appear weaker in older eras. In interwar, it's baerly visible at all, while early and mid war have it reduced compared to latewar. Haven't checked WWI. It is somewhat annoying, not vital for the game to function, but frustrating nontheless, especially with how good it looks in later eras.

**Version**
 Geometric internals test, since eras were added back.

**To Reproduce**
1. Go to Geometric internals beta.
2. Make any functional tank with an exhaust pipe.
3. Drive, observe the exhaust.

**Expected behavior**
 Exhaust smoke appears normally.

**Screenshots**

![20241002224521_1](https://github.com/user-attachments/assets/6f92a546-5751-41f6-b243-80dfaa80de55)
![20241002224507_1](https://github.com/user-attachments/assets/03222cad-50cf-4555-8e41-03779f9baa28)

**Comment by Muushy** [comment]
Fixed in 0.2.20
