### ISSUE TITLE
Stock vehicles have flat front

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#639]
**Describe the bug**
Since this was an unreported change, I'm filing it here in case this was unintentional.
All stock vehicles now start like this.
![image](https://github.com/user-attachments/assets/227125e0-cf26-456d-a883-ad90c9e1633f)

**Version**
0.2.19.1

**Comment by Muushy** [comment]
Fixed in 0.2.19.4
