### ISSUE TITLE
Oriented turrets don't aim in the expected direction

### ISSUE THREAD

**Issue by Harbisonel** [Muushy/Sprocket-Feedback#640]
**Describe the bug**
 Turrets rotated in the vehicle editor will fix their rotation in game to rotation in editor, meaning that turrets rotated to face backwards by defaul, in the editor, will also aim backwards and opposite to where the player is looking.
 
 In other words, rotating turrets to face sideways or backwards breaks them, which is an issue for multi turreted tanks, especially for rotation restrictions on rearmost turrets.

 This extends to aiming itself: A turret rotated 180 degrees will have inverted horizontal traverse, so moving the mouse right make the turret go left.

**Version**
 Geometric internals beta.

**To Reproduce**
1. Play Geometric beta.
2. Make a tank with at least two turrets.
3. Make sure at least one turret is rotatbed to be facing backwards in the editor.
4. Try to aim the backwards turret.

**Expected behavior**
 Turrets rotated bakc worked in 0.127 and overall in pre-geometric versions as they should: even turrets rotated in the editor would target correctly.

**Screenshots**

Notice the rear turret looking opposite side to the two front ones.

![20241007224801_1](https://github.com/user-attachments/assets/1f4b84c9-e153-496e-806f-f1c4a2c13757)
![20241007224751_1](https://github.com/user-attachments/assets/25e21480-1c40-426b-9942-97334b66d103)
![20241007224758_1](https://github.com/user-attachments/assets/73731660-c5b4-42d1-9356-1c2a6cfd8635)

**Comment by Muushy** [comment]
Fixed in 0.2.21
