### ISSUE TITLE
Reduce the recoil of guns to 1/2 what it is now

### ISSUE THREAD

**Issue by robotnikthingy** [Muushy/Sprocket-Feedback#641]
**Is your feature request related to a problem? Please describe.**
Right now, its hard to contain guns within the turrets of tanks without making them unneccessarily long, and interferes with historical designs

**Describe the solution you'd like**
Until recoil dampening mechanics and mechanisms are added, I propose reducing the recoil to 1/2 of what it currently is now. I came to this conclusion by looking at the interior of turrets from tanks such as the IS-2

If we are to go by the recoil guard on the IS-2 tank, the recoil of the gun is about twice the length of the breech block
![23985767926_3e410af574_o](https://github.com/user-attachments/assets/959ed204-d025-4217-b7a1-4d4211187281)

Compared to in game right now on a replication of the IS-2 firing the same 122x785 ammo, where its twice as long
![image](https://github.com/user-attachments/assets/ec879b99-cf8b-46f7-8bef-9b6917a157d7)

Its a rough estimate, but would much more accurately match the historical recoil of the majority of guns, and make designing historical designs and replicas more easier

**Describe alternatives you've considered**

**Additional context**
This is all done in the .20 alpha released on 10/7/24

**Comment by IllyStable** [comment]
I dont believe that distance is recoil - it's dependant on the shell dimensions making me think it's the space needed to push the shell into the breech. The IS-2 used 2 part ammo which is why it's turret shape wasn't impacted by this.

**Comment by Harbisonel** [comment]
> I dont believe that distance is recoil - it's dependant on the shell dimensions making me think it's the space needed to push the shell into the breech. The IS-2 used 2 part ammo which is why it's turret shape wasn't impacted by this.

Yes, that's exactly what it is.

Space needed for loading.

I don't think recoil is even simulated when it comes to internal management, it's only cosmetic for now.

**Comment by robotnikthingy** [comment]
> > I dont believe that distance is recoil - it's dependant on the shell dimensions making me think it's the space needed to push the shell into the breech. The IS-2 used 2 part ammo which is why it's turret shape wasn't impacted by this.
> 
> Yes, that's exactly what it is.
> 
> Space needed for loading.
> 
> I don't think recoil is even simulated when it comes to internal management, it's only cosmetic for now.



> I dont believe that distance is recoil - it's dependant on the shell dimensions making me think it's the space needed to push the shell into the breech. The IS-2 used 2 part ammo which is why it's turret shape wasn't impacted by this.

I think i see what your saying, that part is the space required to load the shell. However, when you hover over the travers gear (box thing with flywheel on it) it shows the recoil for tge breech itself as well, which is rather large.

Im not at my computer so I cant upload a screenshot at the moment

**Comment by IllyStable** [comment]
I believe that's still the shell loading range, just it shows as an arch this time because its the loading area at every angle of elevation.

**Comment by robotnikthingy** [comment]
Nevermind you guys are right. The part I was talking about was the breech block hit box, doesn't look like recoil affects it

![image](https://github.com/user-attachments/assets/009631af-e435-497e-a106-ea72a8fecc88)
