### ISSUE TITLE
Freeform position sliders are incorrectly labeled

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#647]
Title, the Y and Z sliders are swapped.

Pressing G and then Z moves things in the Y axis and pressing G and then Y moves things in the Z axis.
This is according to the position sliders, the actual action is correct.

![image](https://github.com/user-attachments/assets/9b75c7d5-4554-48c8-b2e3-6fb764688599)

**Comment by Muushy** [comment]
Fixed in 0.2.25
