### ISSUE TITLE
Disabling track tail effects in settings does not remove the track tail terrain layer

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#654]
**Describe the bug**
When turning off track tail effects, the terrain layer that gets "imprinted" by the tracks still exists - you just clip directly into it.  This bug was also present in 0.127, and required a bunch of fancy steps to fully remove it.

**Version**
0.2.20.0

**Comment by Muushy** [comment]
Fixed in 0.2.20.3
