### ISSUE TITLE
Paint panel UI does not appear when other UI is open.

### ISSUE THREAD

**Issue by goldloti2** [Muushy/Sprocket-Feedback#658]
**Describe the bug**
When other UI is open, Paint panel won't appear. You must deselect the current part before selecting the Paint panel.

**Version**
0.2.19.5

**To Reproduce**
1. Select any part
2. Click on 'Paint'
3. See error

**Expected behavior**
Panel UI should switch to 'Paint'

**Screenshots**
![image](https://github.com/user-attachments/assets/124079b8-2bbd-4a62-a071-91fcaa2c15b3)

**Comment by Muushy** [comment]
Fixed in 0.2.21
