### ISSUE TITLE
Deleting all faces of the hull leaves an unselectable plate

### ISSUE THREAD

**Issue by SprocketTools** [Muushy/Sprocket-Feedback#662]
**Describe the bug**
When deleting all freeform faces from a hull, the leftover face cannot be selected nor have objects placed onto it.  Restarting seems to help.

**Version**
0.2.20

![image](https://github.com/user-attachments/assets/f1b2f3a2-0fac-4862-90ae-6f0fef64fea2)

**Comment by DarioXN** [comment]
Can confirm having experienced this.

**Comment by Muushy** [comment]
Fixed in 0.2.21
