### ISSUE TITLE
The motion of the camera returning to a horizontal position will be visible

### ISSUE THREAD

**Issue by goldloti2** [Muushy/Sprocket-Feedback#673]
**Describe the bug**
The motion of the camera returning to a horizontal position will be visible when entering or exiting snipe mode if the cannon breech is tilted. Only the first time enter the snipe mode in a scenario, but every time when exit the snipe mode.

**Version**
0.2.20

**To Reproduce**
1. place a cannon breech and tilt it, like the one in M18.
2. place other essentials like crew and sight.
3. start the scenario and enter/exit snipe mode

**Expected behavior**
The camera should always be horizontal.

**Comment by Muushy** [comment]
Fixed in 0.2.23
