### ISSUE TITLE
Ammo rack can select the ammo of deleted guns

### ISSUE THREAD

**Issue by goldloti2** [Muushy/Sprocket-Feedback#680]
**Describe the bug**
The ammo of deleted guns can still be selected in ammo rack UI, even on newly placed ammo rack.
If there are two identical guns, there are two identical ammo can be selected, even though they can be loaded into both guns.

**Version**
0.2.21.4

**To Reproduce**
1. Place a gun and set it caliber to 150 (or other than default one).
2. Delete the gun.
3. Place a new gun and an ammo rack.
4. Select the ammo rack, choose the ammo and see error.

**Expected behavior**
Only the ammo of the carried guns can be selected. If there are two identical guns, it should show only one ammo.

**Screenshots**
There are two 120x800 and one 250x1190, and 20x500 is the deleted one. (I don't know what's the cause of the 3rd 120x800)
![image](https://github.com/user-attachments/assets/4c5df042-4dc0-4ea5-81f9-e448a7520dec)

**Comment by Muushy** [comment]
Fixed in 0.2.25
