### ISSUE TITLE
Ammo Dissapearing after duplication without placing

### ISSUE THREAD

**Issue by Raichor** [Muushy/Sprocket-Feedback#682]
**Describe the bug**
Ammo dissapears when saving/loading/driving the vehicle if it has been duplicated. The duplicated ammo retains an orange box around it until something (can be anything) is placed/moved by picking it with the mouse. Any ammo with this orange box is removed when saving/loading/driving.

**Version**
0.2.21.4

**To Reproduce**
1. Place ammo
2. Duplicate the placed ammo using the translation tool whilst holding alt
3. Press space to drive the tank
4. Duplicated ammo disappears

**Expected behavior**
Duplicated ammo should not disappear.

**Video**
https://www.youtube.com/watch?v=pNVnHalpIYM

**Comment by Muushy** [comment]
Issue was present when using this duplication method on _any_ part. Resulted in a lot of instability.
Fixed in 0.2.22.
