### ISSUE TITLE
More options for armour visibility in internal view (Possible bug as well)

### ISSUE THREAD

**Issue by Raichor** [Muushy/Sprocket-Feedback#686]
### **Is your feature request related to a problem? Please describe.**
Armour can often occlude many parts of a vehicle in internal view (particularly when modelling composites). The new overlay config for internal view is great, however, toggling armour visibility, only changes visibility for the front faces of armour.

**Possible bug**
Additionally, in internal view, the default config setting for armour is "on", whilst the default visibilty state for the armour seems to be "off" (front faces are hidden). As a result initially toggling armour visibilty to "off" does nothing as it is already "off", toggling again to "on" shows front faces as expected.

### **Describe the solution you'd like**
Have two options for armour visibility in internal view, one for toggling visibility of back/side faces and one for toggling front faces.

### **Describe alternatives you've considered**
Could instead change the default behaviour to use the front face hidden mode as the default "on" state for armour in internal view, with the "off" state completely hiding the armour.

**Comment by Muushy** [comment]
Implemented in 0.2.23
'Plate structure' filter split into 'Exterior' and 'Interior' with the described functionality.
