### ISSUE TITLE
premade turret replacing freeform

### ISSUE THREAD

**Issue by akuakuakuakuakuaku** [Muushy/Sprocket-Feedback#715]
**Describe the bug**
premade turret replacing freeform

**Version**
0.2.24.7

**To Reproduce**
1.1 make a new bp
2.1 get rid of the current pre gen hull and save the base freeform square plate as a bp
3.1 open the bp you just saved and select the square face in editor
4.1 click turret while in editor, and it replaces the freeform you did and you cant undo.

it can also happen in the middle of building like so especially if you accidentally do this before saving as theres no way to undo it unless you have a older save.

2.1 make a new bp and select the hull click turret
2.2 save bp and reload
3.3 when reloading bp the hull will be the pre gen turret

**Expected behavior**
pre gen turret

**Screenshots**
N/A

**Additional context**
two videos showing this happening on last version and it persists in current 
https://discord.com/channels/788349365466038283/879446071007379476/1317424304677326869
https://discord.com/channels/788349365466038283/879446071007379476/1317425240082743349

**Comment by Muushy** [comment]
Thanks for the report!
Fixed in 0.2.25
