### ISSUE TITLE
Splitting T-Shaped Geometry creates n-gon

### ISSUE THREAD

**Issue by Raichor** [Muushy/Sprocket-Feedback#716]
**Describe the bug**
When you split the vertical edge of a T-join of faces it creates an n-gon (verified by looking at corrupted vehicle file). This causes the game to hang and prevents expected functionality for many features of the editor until the game is restarted. Additionaly if you save after splitting, the vehicle file becomes unable to load until the n-gon face is deleted through file editing.

**Version**
0.2.24.7

**To Reproduce**
1. Create addon structure with a single face.
2. Extrude edge in one direction
3. Reselect edge and extrude in opposite direction
4. Split edge

**Expected behavior**
Edge should split all 3 connected faces, alternatively edge splitting should be disabled for edges with more than 2 connected faces.

**Screenshots**
Geometry:
![image](https://github.com/user-attachments/assets/15d11a22-047d-4d8e-bf0a-60eb3d8b720c)
Face data pre (column 1) and post (column 2/3) split (highlighted 5 vertex n-gon)
![image](https://github.com/user-attachments/assets/4ee2da0a-901f-4212-876d-386d22c72652)

**Additional context**
Maybe issue with splitting function expecting 2 connected faces on the edge when instead there are 3?

**Comment by Muushy** [comment]
Thanks for the detailed report!
Fixed in 0.2.25
Splitting a face loop capped by an edge connected to more than two faces will fail correctly and send an error message.
