### ISSUE TITLE
Sherman gun mantlet al lower scales

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#74]
The mantlet has it's gun move upwards relative to the hole when scaling it to a smaller size, the gun also floats in front of the mantlet when doing this.
![image](https://user-images.githubusercontent.com/109303520/179126041-7ee3c9b9-8468-4804-8217-31a75ab49a3f.png)

**Comment by Muushy** [comment]
Fixed in V0.11913
