### ISSUE TITLE
Placement tool incorrect axis moving parts on non-upright turrets

### ISSUE THREAD

**Issue by Muushy** [Muushy/Sprocket-Feedback#80]
**Describe the bug**
Parts placed on non-upright turrets wont move in the direction of the chosen placement tool axis. They move on a different axis instead.

**Comment by Muushy** [comment]
Fixed in V0.11916

**Comment by DarioXN** [comment]
This one has recently re-emerged

**Comment by Muushy** [comment]
Fixed in V0.12419.
