### ISSUE TITLE
Tank fake dies when loader is knocked out

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#82]
When the loader is knocked out the tank dies, but you can turn it's engine back on and then drive again.
Enemies don't attack you anymore, you can't aim or shoot anymore, but you can drive.
Note the current speed in the image, and the ally counter being 0.
Gun was loaded at the time the tank got "knocked out".
![image](https://user-images.githubusercontent.com/109303520/179343534-7f6da188-a015-40b9-87a3-2cea204a3c78.png)

**Comment by Muushy** [comment]
Fixed in V0.11914
