### ISSUE TITLE
Tracks wrapping around sprocket/idler poorly at extreme scales

### ISSUE THREAD

**Issue by A1ex-Andro** [Muushy/Sprocket-Feedback#86]
**Describe the bug**
The circle that the track wraps around doesn't scale correctly with sprocket diameter. It is scaled correctly only for a Sprocket diameter of 1.00 metres. For diameters less than 1.00 m the track clips into the sprocket, as shown in the first picture. For diameters greater than 1.00 the result is shown in the second picture.

![image](https://user-images.githubusercontent.com/109421040/179356455-0b2e06b0-0b56-4f33-9eab-cfabb8e4a6b6.png)
![image](https://user-images.githubusercontent.com/109421040/179356463-f87cb096-3f3e-42bd-b730-746356e56daf.png)

**Expected behavior**
The track should wrap around the rim of the sprocket, and be constrained to move along an arc that follows the sprocket's pitch diameter. It would also make sense if the sprocket diameter that the user adjusts in-game was the pitch diameter, not the outside diameter of the sprocket. As shown in the picture below, a sprocket's pitch diameter is the diameter of a circle passing through the track pins' centres. It is this diameter that is used to calculate the linear speed of the tank from the rotation speed of the sprocket. The outside diameter is irrelevant.

![image](https://user-images.githubusercontent.com/109421040/179356881-37e8ddac-5f80-47c9-98d7-c713745f8987.png)

It would be ideal if changing the "sprocket diameter" setting in-game would change the diameter of the circle to which the track is aligned to (ie, the arc along which the track is constrained to move should follow the pitch diameter), and the sprocket itself were to scale correctly such that its rim would conform to the track's edge.

**Comment by Muushy** [comment]
Significantly improved with V0.125x belt wrapping changes.
