### ISSUE TITLE
Gun azimuth stuck to the left

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#87]
Guns with azimuth get stuck with both left and right azimuth having negative limits.
This happens most often on small vehicles.
![image](https://user-images.githubusercontent.com/109303520/179456460-09ebc263-e07c-489a-9f30-b4998a88ab19.png)

Azimuth slider is stuck and the gun cannot move when playing.
![image](https://user-images.githubusercontent.com/109303520/179456709-367df179-1c73-45de-b7fc-b99f1c6cf406.png)

![image](https://user-images.githubusercontent.com/109303520/179456803-7e2cc274-f5e4-4e7e-a654-9b7fc682d5e9.png)

Example Blueprint:
[L3_33_C.zip](https://github.com/Muushy/Sprocket-Feedback/files/9129925/L3_33_C.zip)
Blueprint from user Coconut Cooler on Discord.

**Comment by Muushy** [comment]
Fixed in V0.11914
