### ISSUE TITLE
Two quick fixes to mobility

### ISSUE THREAD

**Issue by A1ex-Andro** [Muushy/Sprocket-Feedback#92]
**1st Problem**

Most transmissions have a single reverse gear. Since it is used for careful manoeuvres such as driving onto train platforms, the maximum speed is very low. In Sprocket, the result is that the driver over-revs the engine to more than double the max rpm and it "explodes" after just a few seconds of trying to drive in reverse.

However, this should not have been a problem as there is already a "target max" in the game, which in theory is the rpm at or below which the driver should try to keep the engine speed.

Logically, a target max of 2500 rpm means that the driver or speed governor should try to keep the engine speed at or below 2500 rpm. As the tank accelerates and the rpm reaches 2500, the driver upshifts to the next gear. If there is no higher gear, the tank should stop accelerating. Instead, the driver tries to over-rev the engine if he can do so!

The engine rpm should be limited to whatever the target max is. It is the *target max*, after all.

**2nd Problem**

I know braking mechanics were planned for a future movement update, but the result of this is that people have been playing the game for almost a year with no way to stop a tank other than to crash into an obstacle or let the resistance forces slow it down. Braking mechanics can definitely wait, but in the meantime there needs to be some other way to stop a tank.

In other games, pressing the reverse key (ie, "D" when going forward) applies an acceleration opposite the direction of movement (for now, the magnitude doesn't matter, just that there is a way to stop the tank), after which the tank will move in the reverse direction. Pressing the "X" key would also decelerate the tank until it stops, but keep it stationary (useful when stopping to fire on a slope).

**Summary**

1. Limit engine rpm to not exceed the target max.
2. Set keybinds to decelerate and stop the tank.

*(Although the best time to fix a problem is at the start, the second best time is as early as possible in the development cycle.)*

**Comment by Muushy** [comment]
Brakes reworked and made configurable in V0.125.
RPM limit added and made configurable in V0.125.
