### ISSUE TITLE
Frequent crashes after 0.11914

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#93]
The game frequently crashes on 0.11914.
Cause unknown, likely designer related.

**Comment by MaxProfessionalLoser** [comment]
> 

I am getting frequent crashes when dealing with cannon and gunner sight + crew assignment. Lights - no matter how few in number, now also destroy my fps (maybe related?)

**Comment by HexagonClientWorker** [comment]
Try to save the compartment, that holds gunner and loader and load it in again.
Check if your crew space goes up.

I have encountered a bug where the loader has only 60% efficiency, but it shows 100% and crashes the game when certain actions are performed.

I just wrote an entire bug report, how to reproduce amd stuff, but i didnt get saved, might try again later...

**Comment by Muushy** [comment]
Fixed in V0.11915
@MaxProfessionalLoser Reverted the engine update in V0.11915. If the light issue persists, would you be able to make a separate issue? Cheers.
