### ISSUE TITLE
Barrel segment shading

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#95]
The front and back parts of barrel segments are incorrectly shaded.
Back is less noticeable, also might be a difference in texture.
Before 0.11914 it was only the back that had this issue.
![image](https://user-images.githubusercontent.com/109303520/180570781-653bc60f-0a8a-4623-a168-6b31da7e791f.png)
![image](https://user-images.githubusercontent.com/109303520/180571152-7f402d69-3a2d-4b31-86ef-044cf1ebec2b.png)

**Comment by Muushy** [comment]
Fixed in V0.11916
