### ISSUE TITLE
Tracks wrapping around sprocket/idler poorly at high scales

### ISSUE THREAD

**Issue by DarioXN** [Muushy/Sprocket-Feedback#99]
Tracks wrap around the top and bottom (less noticeable) of the sprocket and idler badly when these wheels are a large diameter.

![image](https://user-images.githubusercontent.com/109303520/181171843-d1379529-0ae5-48ce-9500-7d334220be40.png)

**Comment by Muushy** [comment]
Dupe of https://github.com/Muushy/Sprocket-Feedback/issues/86
